In [1]:
import os

print(os.getcwd())

/home/jupyter-itproject2026/TrustSOC/notebooks

In [2]:
import os

project_root = "/home/jupyter-itproject2026/TrustSOC"

for path in [
    project_root,
    f"{project_root}/data",
    f"{project_root}/data/raw",
    f"{project_root}/data/raw/cicids2017",
]:
    print("\n", path)
    if os.path.exists(path):
        print(os.listdir(path))
    else:
        print("NOT FOUND")

 /home/jupyter-itproject2026/TrustSOC
['.ipynb_checkpoints', 'notebooks', 'evaluation', 'rag', 'decision', 'backend', 'agents', 'data']

 /home/jupyter-itproject2026/TrustSOC/data
['.ipynb_checkpoints', 'knowledge_base', 'processed', 'raw']

 /home/jupyter-itproject2026/TrustSOC/data/raw
['.ipynb_checkpoints', 'cicids2017']

 /home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017
['.ipynb_checkpoints', 'MachineLearningCVE']

In [3]:
import os

csv_path = "/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Monday-WorkingHours.pcap_ISCX.csv"

print("Exists:", os.path.exists(csv_path))

if os.path.exists(csv_path):
    print("Size:", os.path.getsize(csv_path) / (1024**2), "MB")

Exists: True
Size: 8.0 MB

In [4]:
import pandas as pd

csv_path = "/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Monday-WorkingHours.pcap_ISCX.csv"

df = pd.read_csv(csv_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (23157, 63)

In [5]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
for i, column in enumerate(df.columns):
    print(i, ":", repr(column))

Number of rows: 23157
Number of columns: 63

Column names:
0 : '0980'
1 : '0'
2 : '170980'
3 : '170980.1'
4 : '0.1'
5 : '0.2'
6 : '0.3'
7 : '0.4'
8 : '0.5'
9 : '0.6'
10 : '0.7'
11 : '0.8'
12 : '0.9'
13 : '0.10'
14 : '0.11'
15 : '0.12'
16 : '0.13'
17 : '0.14'
18 : '32'
19 : '32.1'
20 : '5.8486372675'
21 : '5.8486372675.1'
22 : '54'
23 : '149'
24 : '85.6666666667'
25 : '54.848275573'
26 : '3008.3333333333'
27 : '0.15'
28 : '0.16'
29 : '0.17'
30 : '0.18'
31 : '0.19'
32 : '0.20'
33 : '0.21'
34 : '0.22'
35 : '1'
36 : '128.5'
37 : '54.1'
38 : '149.1'
39 : '32.2'
40 : '0.23'
41 : '0.24'
42 : '0.25'
43 : '0.26'
44 : '0.27'
45 : '0.28'
46 : '1.1'
47 : '54.2'
48 : '1.2'
49 : '149.2'
50 : '-1'
51 : '-1.1'
52 : '0.29'
53 : '32.3'
54 : '0.30'
55 : '0.31'
56 : '0.32'
57 : '0.33'
58 : '0.34'
59 : '0.35'
60 : '0.36'
61 : '0.37'
62 : 'BENIGN'

In [6]:
display(df.head())

                                                                                         0980  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     16249.333333
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020     40793.000000
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728     68.666667
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    10376.000000
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846    16422.000000

                                                                                            0  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     28100.513453
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020         0.000000
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728    112.873085
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    17965.697008
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846        0.000000

                                                                                 170980  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      48697
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      40793
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728     199
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     31121
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     16422

                                                                                 170980.1  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648            2
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020        40793
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728         3
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671           3
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846       16422

                                                                                 0.1  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648       2
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020       0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728    3
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671      3
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846      0

                                                                                 0.2  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     2.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020     0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728  3.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    3.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846    0.0

                                                                                 0.3  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020     0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728  0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846    0.0

                                                                                 0.4  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648       2
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020       0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728    3
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671      3
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846      0

                                                                                 0.5  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648       2
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020       0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728    3
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671      3
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846      0

                                                                                 0.6  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      49
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020       0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728    4
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671      4
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846      0

                                                                                 ...  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     ...
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020     ...
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728  ...
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    ...
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846    ...

                                                                                 32.3  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     20.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020     20.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728  20.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    32.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846    32.0

                                                                                 0.30  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.31  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.32  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.33  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.34  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.35  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.36  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 0.37  \
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648      0.0
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020      0.0
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728   0.0
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671     0.0
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846     0.0

                                                                                 BENIGN
53  48748 2 2 92 170 46 46 46.0 0.0 85  85  85.0  0.0 5.374579e+03 82.054648     BENIGN
    40793 1 1 44 122 44 44 44.0 0.0 122 122 122.0 0.0 4.069326e+03 49.028020     BENIGN
    206   2 2 94 350 47 47 47.0 0.0 175 175 175.0 0.0 2.155340e+06 19417.475728  BENIGN
    31128 2 2 72 128 36 36 36.0 0.0 64  64  64.0  0.0 6.425084e+03 128.501671    BENIGN
123 16422 1 1 48 48  48 48 48.0 0.0 48  48  48.0  0.0 5.845817e+03 121.787846    BENIGN

[5 rows x 63 columns]

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
MultiIndex: 23157 entries, (np.int64(53), np.int64(48748), np.int64(2), np.int64(2), np.int64(92), np.int64(170), np.int64(46), np.int64(46), np.float64(46.0), np.float64(0.0), np.int64(85), np.int64(85), np.float64(85.0), np.float64(0.0), np.float64(5374.579469927), np.float64(82.0546483958)) to (np.int64(443), np.int64(61178524), np.int64(15), np.int64(12), np.int64(1354), np.int64(420), np.int64(1076), np.int64(0), np.float64(90.2666666667), np.float64(278.988598504), np.int64(244), np.int64(0), np.float64(35.0), np.float64(77.9405367747), np.float64(28.9971036241), np.float64(0.4413313404))
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   0980             23157 non-null  float64
 1   0                23157 non-null  float64
 2   170980           23157 non-null  int64
 3   170980.1         23157 non-null  int64
 4   0.1              23157 non-null  int64
 5   0.2              23157 non-null  float64
 6   0.3              23157 non-null  float64
 7   0.4              23157 non-null  int64
 8   0.5              23157 non-null  int64
 9   0.6              23157 non-null  int64
 10  0.7              23157 non-null  float64
 11  0.8              23157 non-null  float64
 12  0.9              23157 non-null  int64
 13  0.10             23157 non-null  int64
 14  0.11             23157 non-null  int64
 15  0.12             23157 non-null  int64
 16  0.13             23157 non-null  int64
 17  0.14             23157 non-null  int64
 18  32               23157 non-null  int64
 19  32.1             23157 non-null  int64
 20  5.8486372675     23157 non-null  float64
 21  5.8486372675.1   23157 non-null  float64
 22  54               23157 non-null  int64
 23  149              23157 non-null  int64
 24  85.6666666667    23157 non-null  float64
 25  54.848275573     23157 non-null  float64
 26  3008.3333333333  23157 non-null  float64
 27  0.15             23157 non-null  int64
 28  0.16             23157 non-null  int64
 29  0.17             23157 non-null  int64
 30  0.18             23157 non-null  int64
 31  0.19             23157 non-null  int64
 32  0.20             23157 non-null  int64
 33  0.21             23157 non-null  int64
 34  0.22             23157 non-null  int64
 35  1                23157 non-null  int64
 36  128.5            23157 non-null  float64
 37  54.1             23156 non-null  float64
 38  149.1            23156 non-null  float64
 39  32.2             23156 non-null  float64
 40  0.23             23156 non-null  float64
 41  0.24             23156 non-null  float64
 42  0.25             23156 non-null  float64
 43  0.26             23156 non-null  float64
 44  0.27             23156 non-null  float64
 45  0.28             23156 non-null  float64
 46  1.1              23156 non-null  float64
 47  54.2             23156 non-null  float64
 48  1.2              23156 non-null  float64
 49  149.2            23156 non-null  float64
 50  -1               23156 non-null  float64
 51  -1.1             23156 non-null  float64
 52  0.29             23156 non-null  float64
 53  32.3             23156 non-null  float64
 54  0.30             23156 non-null  float64
 55  0.31             23156 non-null  float64
 56  0.32             23156 non-null  float64
 57  0.33             23156 non-null  float64
 58  0.34             23156 non-null  float64
 59  0.35             23156 non-null  float64
 60  0.36             23156 non-null  float64
 61  0.37             23156 non-null  float64
 62  BENIGN           23156 non-null  str
dtypes: float64(37), int64(25), str(1)
memory usage: 12.5 MB
None

In [8]:
with open(csv_path, "r", encoding="utf-8", errors="replace") as f:
    for i in range(5):
        print(f"LINE {i + 1}:")
        print(repr(f.readline()))

LINE 1:
'0980,0,170980,170980,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,32,5.8486372675,5.8486372675,54,149,85.6666666667,54.848275573,3008.3333333333,0,0,0,0,0,0,0,0,1,128.5,54,149,32,0,0,0,0,0,0,1,54,1,149,-1,-1,0,32,0,0,0,0,0,0,0,0,BENIGN\n'
LINE 2:
'53,48748,2,2,92,170,46,46,46,0,85,85,85,0,5374.579469927,82.0546483958,16249.3333333333,28100.5134531975,48697,2,2,2,0,2,2,49,49,0,49,49,0,0,0,0,40,112,41.0273241979,41.0273241979,46,85,61.6,21.3611797427,456.3,0,0,0,0,0,0,0,0,1,77,46,85,40,0,0,0,0,0,0,2,92,2,170,-1,-1,1,20,0,0,0,0,0,0,0,0,BENIGN\n'
LINE 3:
'53,40793,1,1,44,122,44,44,44,0,122,122,122,0,4069.3256195916,49.0280195132,40793,0,40793,40793,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,20,24.5140097566,24.5140097566,44,122,70,45.0333209968,2028,0,0,0,0,0,0,0,0,1,105,44,122,20,0,0,0,0,0,0,1,44,1,122,-1,-1,0,20,0,0,0,0,0,0,0,0,BENIGN\n'
LINE 4:
'53,206,2,2,94,350,47,47,47,0,175,175,175,0,2155339.80582524,19417.4757281553,68.6666666667,112.8730850705,199,3,3,3,0,3,3,4,4,0,4,4,0,0,0,0,40,40,9708.7378640777,9708.7378640777,47,175,98.2,70.1084873607,4915.2,0,0,0,0,0,0,0,0,1,122.75,47,175,40,0,0,0,0,0,0,2,94,2,350,-1,-1,1,20,0,0,0,0,0,0,0,0,BENIGN\n'
LINE 5:
'53,31128,2,2,72,128,36,36,36,0,64,64,64,0,6425.0835260858,128.5016705217,10376,17965.6970084659,31121,3,3,3,0,3,3,4,4,0,4,4,0,0,0,0,64,64,64.2508352609,64.2508352609,36,64,47.2,15.3362316101,235.2,0,0,0,0,0,0,0,0,1,59,36,64,64,0,0,0,0,0,0,2,72,2,128,-1,-1,1,32,0,0,0,0,0,0,0,0,BENIGN\n'

In [9]:
with open(csv_path, "r", encoding="utf-8", errors="replace") as f:
    for i in range(10):
        line = f.readline().strip()
        values = line.split(",")

        print(f"Line {i + 1}: {len(values)} fields")
        print("First 3:", values[:3])
        print("Last 3:", values[-3:])
        print()

Line 1: 63 fields
First 3: ['0980', '0', '170980']
Last 3: ['0', '0', 'BENIGN']

Line 2: 79 fields
First 3: ['53', '48748', '2']
Last 3: ['0', '0', 'BENIGN']

Line 3: 79 fields
First 3: ['53', '40793', '1']
Last 3: ['0', '0', 'BENIGN']

Line 4: 79 fields
First 3: ['53', '206', '2']
Last 3: ['0', '0', 'BENIGN']

Line 5: 79 fields
First 3: ['53', '31128', '2']
Last 3: ['0', '0', 'BENIGN']

Line 6: 79 fields
First 3: ['123', '16422', '1']
Last 3: ['0', '0', 'BENIGN']

Line 7: 79 fields
First 3: ['53', '32416', '2']
Last 3: ['0', '0', 'BENIGN']

Line 8: 79 fields
First 3: ['5058', '20732', '5']
Last 3: ['0', '0', 'BENIGN']

Line 9: 79 fields
First 3: ['443', '613042', '8']
Last 3: ['0', '0', 'BENIGN']

Line 10: 79 fields
First 3: ['80', '84770868', '12']
Last 3: ['10217109', '10164126', 'BENIGN']

In [10]:
from collections import Counter

field_counts = Counter()

with open(csv_path, "r", encoding="utf-8", errors="replace") as f:
    for line_number, line in enumerate(f, start=1):
        count = len(line.rstrip("\n").split(","))
        field_counts[count] += 1

print(field_counts)

Counter({79: 23156, 63: 1, 53: 1})

In [11]:
import os

raw_folder = "/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017"

for root, dirs, files in os.walk(raw_folder):
    for file in files:
        print(os.path.join(root, file))

/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Morning.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Wednesday-workingHours.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Monday-WorkingHours.pcap_ISCX.csv
/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv

In [12]:
import os

cve_folder = "/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE"

files = os.listdir(cve_folder)

print("Files:")
for file in files:
    print(file)

Files:
Friday-WorkingHours-Morning.pcap_ISCX.csv
.ipynb_checkpoints
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Wednesday-workingHours.pcap_ISCX.csv
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Monday-WorkingHours.pcap_ISCX.csv
Tuesday-WorkingHours.pcap_ISCX.csv

In [13]:
import os
from collections import Counter

cve_folder = "/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE"

for filename in sorted(os.listdir(cve_folder)):
    if not filename.endswith(".csv"):
        continue

    filepath = os.path.join(cve_folder, filename)

    counts = Counter()

    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            counts[len(line.rstrip("\n").split(","))] += 1

    print(f"\n{filename}")
    print(f"Rows by field count: {counts}")

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Rows by field count: Counter({79: 1935, 20: 1})

Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Rows by field count: Counter({79: 30145, 62: 1})

Friday-WorkingHours-Morning.pcap_ISCX.csv
Rows by field count: Counter({79: 191034})

Monday-WorkingHours.pcap_ISCX.csv
Rows by field count: Counter({79: 23156, 63: 1, 53: 1})

Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Rows by field count: Counter({79: 35223, 63: 1})

Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Rows by field count: Counter({79: 170367})

Tuesday-WorkingHours.pcap_ISCX.csv
Rows by field count: Counter({79: 209817, 27: 1})

Wednesday-workingHours.pcap_ISCX.csv
Rows by field count: Counter({79: 185944, 24: 1})

In [14]:
import pandas as pd

friday_path = "/home/jupyter-itproject2026/TrustSOC/data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Morning.pcap_ISCX.csv"

df_test = pd.read_csv(
    friday_path,
    header=None,
    low_memory=False
)

print("Shape:", df_test.shape)
print("\nFirst row:")
print(df_test.iloc[0].tolist())

print("\nLast 5 columns:")
print(df_test.iloc[0, -5:].tolist())

Shape: (191034, 79)

First row:
[' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']

Last 5 columns:
['Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']

In [15]:
df = pd.read_csv(
    friday_path,
    low_memory=False
)

print("Shape:", df.shape)

print("\nColumns:")
for i, col in enumerate(df.columns):
    print(i, ":", repr(col))

print("\nLabels:")
print(df[" Label"].value_counts())

Shape: (191033, 79)

Columns:
0 : ' Destination Port'
1 : ' Flow Duration'
2 : ' Total Fwd Packets'
3 : ' Total Backward Packets'
4 : 'Total Length of Fwd Packets'
5 : ' Total Length of Bwd Packets'
6 : ' Fwd Packet Length Max'
7 : ' Fwd Packet Length Min'
8 : ' Fwd Packet Length Mean'
9 : ' Fwd Packet Length Std'
10 : 'Bwd Packet Length Max'
11 : ' Bwd Packet Length Min'
12 : ' Bwd Packet Length Mean'
13 : ' Bwd Packet Length Std'
14 : 'Flow Bytes/s'
15 : ' Flow Packets/s'
16 : ' Flow IAT Mean'
17 : ' Flow IAT Std'
18 : ' Flow IAT Max'
19 : ' Flow IAT Min'
20 : 'Fwd IAT Total'
21 : ' Fwd IAT Mean'
22 : ' Fwd IAT Std'
23 : ' Fwd IAT Max'
24 : ' Fwd IAT Min'
25 : 'Bwd IAT Total'
26 : ' Bwd IAT Mean'
27 : ' Bwd IAT Std'
28 : ' Bwd IAT Max'
29 : ' Bwd IAT Min'
30 : 'Fwd PSH Flags'
31 : ' Bwd PSH Flags'
32 : ' Fwd URG Flags'
33 : ' Bwd URG Flags'
34 : ' Fwd Header Length'
35 : ' Bwd Header Length'
36 : 'Fwd Packets/s'
37 : ' Bwd Packets/s'
38 : ' Min Packet Length'
39 : ' Max Packet Length'
40 : ' Packet Length Mean'
41 : ' Packet Length Std'
42 : ' Packet Length Variance'
43 : 'FIN Flag Count'
44 : ' SYN Flag Count'
45 : ' RST Flag Count'
46 : ' PSH Flag Count'
47 : ' ACK Flag Count'
48 : ' URG Flag Count'
49 : ' CWE Flag Count'
50 : ' ECE Flag Count'
51 : ' Down/Up Ratio'
52 : ' Average Packet Size'
53 : ' Avg Fwd Segment Size'
54 : ' Avg Bwd Segment Size'
55 : ' Fwd Header Length.1'
56 : 'Fwd Avg Bytes/Bulk'
57 : ' Fwd Avg Packets/Bulk'
58 : ' Fwd Avg Bulk Rate'
59 : ' Bwd Avg Bytes/Bulk'
60 : ' Bwd Avg Packets/Bulk'
61 : 'Bwd Avg Bulk Rate'
62 : 'Subflow Fwd Packets'
63 : ' Subflow Fwd Bytes'
64 : ' Subflow Bwd Packets'
65 : ' Subflow Bwd Bytes'
66 : 'Init_Win_bytes_forward'
67 : ' Init_Win_bytes_backward'
68 : ' act_data_pkt_fwd'
69 : ' min_seg_size_forward'
70 : 'Active Mean'
71 : ' Active Std'
72 : ' Active Max'
73 : ' Active Min'
74 : 'Idle Mean'
75 : ' Idle Std'
76 : ' Idle Max'
77 : ' Idle Min'
78 : ' Label'

Labels:
 Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

In [16]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 191033 entries, 0 to 191032
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             191033 non-null  int64
 1    Flow Duration                191033 non-null  int64
 2    Total Fwd Packets            191033 non-null  int64
 3    Total Backward Packets       191033 non-null  int64
 4   Total Length of Fwd Packets   191033 non-null  int64
 5    Total Length of Bwd Packets  191033 non-null  int64
 6    Fwd Packet Length Max        191033 non-null  int64
 7    Fwd Packet Length Min        191033 non-null  int64
 8    Fwd Packet Length Mean       191033 non-null  float64
 9    Fwd Packet Length Std        191033 non-null  float64
 10  Bwd Packet Length Max         191033 non-null  int64
 11   Bwd Packet Length Min        191033 non-null  int64
 12   Bwd Packet Length Mean       191033 non-null  float64
 13   Bwd Packet Length Std        191033 non-null  float64
 14  Flow Bytes/s                  191005 non-null  float64
 15   Flow Packets/s               191033 non-null  float64
 16   Flow IAT Mean                191033 non-null  float64
 17   Flow IAT Std                 191033 non-null  float64
 18   Flow IAT Max                 191033 non-null  int64
 19   Flow IAT Min                 191033 non-null  int64
 20  Fwd IAT Total                 191033 non-null  int64
 21   Fwd IAT Mean                 191033 non-null  float64
 22   Fwd IAT Std                  191033 non-null  float64
 23   Fwd IAT Max                  191033 non-null  int64
 24   Fwd IAT Min                  191033 non-null  int64
 25  Bwd IAT Total                 191033 non-null  int64
 26   Bwd IAT Mean                 191033 non-null  float64
 27   Bwd IAT Std                  191033 non-null  float64
 28   Bwd IAT Max                  191033 non-null  int64
 29   Bwd IAT Min                  191033 non-null  int64
 30  Fwd PSH Flags                 191033 non-null  int64
 31   Bwd PSH Flags                191033 non-null  int64
 32   Fwd URG Flags                191033 non-null  int64
 33   Bwd URG Flags                191033 non-null  int64
 34   Fwd Header Length            191033 non-null  int64
 35   Bwd Header Length            191033 non-null  int64
 36  Fwd Packets/s                 191033 non-null  float64
 37   Bwd Packets/s                191033 non-null  float64
 38   Min Packet Length            191033 non-null  int64
 39   Max Packet Length            191033 non-null  int64
 40   Packet Length Mean           191033 non-null  float64
 41   Packet Length Std            191033 non-null  float64
 42   Packet Length Variance       191033 non-null  float64
 43  FIN Flag Count                191033 non-null  int64
 44   SYN Flag Count               191033 non-null  int64
 45   RST Flag Count               191033 non-null  int64
 46   PSH Flag Count               191033 non-null  int64
 47   ACK Flag Count               191033 non-null  int64
 48   URG Flag Count               191033 non-null  int64
 49   CWE Flag Count               191033 non-null  int64
 50   ECE Flag Count               191033 non-null  int64
 51   Down/Up Ratio                191033 non-null  int64
 52   Average Packet Size          191033 non-null  float64
 53   Avg Fwd Segment Size         191033 non-null  float64
 54   Avg Bwd Segment Size         191033 non-null  float64
 55   Fwd Header Length.1          191033 non-null  int64
 56  Fwd Avg Bytes/Bulk            191033 non-null  int64
 57   Fwd Avg Packets/Bulk         191033 non-null  int64
 58   Fwd Avg Bulk Rate            191033 non-null  int64
 59   Bwd Avg Bytes/Bulk           191033 non-null  int64
 60   Bwd Avg Packets/Bulk         191033 non-null  int64
 61  Bwd Avg Bulk Rate             191033 non-null  int64
 62  Subflow Fwd Packets           191033 non-null  int64
 63   Subflow Fwd Bytes            191033 non-null  int64
 64   Subflow Bwd Packets          191033 non-null  int64
 65   Subflow Bwd Bytes            191033 non-null  int64
 66  Init_Win_bytes_forward        191033 non-null  int64
 67   Init_Win_bytes_backward      191033 non-null  int64
 68   act_data_pkt_fwd             191033 non-null  int64
 69   min_seg_size_forward         191033 non-null  int64
 70  Active Mean                   191033 non-null  float64
 71   Active Std                   191033 non-null  float64
 72   Active Max                   191033 non-null  int64
 73   Active Min                   191033 non-null  int64
 74  Idle Mean                     191033 non-null  float64
 75   Idle Std                     191033 non-null  float64
 76   Idle Max                     191033 non-null  int64
 77   Idle Min                     191033 non-null  int64
 78   Label                        191033 non-null  str
dtypes: float64(24), int64(54), str(1)
memory usage: 115.1 MB
None

In [17]:
print(df.head(3))

    Destination Port   Flow Duration   Total Fwd Packets  \
0               3268       112740690                  32
1                389       112740560                  32
2                  0       113757377                 545

    Total Backward Packets  Total Length of Fwd Packets  \
0                       16                         6448
1                       16                         6448
2                        0                            0

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                          1152                     403
1                          5056                     403
2                             0                       0

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       0                    201.5              204.724205
1                       0                    201.5              204.724205
2                       0                      0.0                0.000000

   ...   min_seg_size_forward   Active Mean    Active Std   Active Max  \
0  ...                     32  3.594286e+02  1.199802e+01          380
1  ...                     32  3.202857e+02  1.574499e+01          330
2  ...                      0  9.361829e+06  7.324646e+06     18900000

    Active Min   Idle Mean      Idle Std   Idle Max   Idle Min   Label
0          343  16100000.0  4.988048e+05   16400000   15400000  BENIGN
1          285  16100000.0  4.987937e+05   16400000   15400000  BENIGN
2           19  12200000.0  6.935824e+06   20800000    5504997  BENIGN

[3 rows x 79 columns]

In [18]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

In [19]:
X = df.drop(columns=["Label"])
y = df["Label"].copy()

print("Feature shape:", X.shape)
print("Label shape:", y.shape)

print("\nLabels:")
print(y.value_counts())

Feature shape: (191033, 78)
Label shape: (191033,)

Labels:
Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

In [20]:
missing = X.isnull().sum()

print(missing[missing > 0])

Flow Bytes/s    28
dtype: int64

In [21]:
import numpy as np

numeric_X = X.select_dtypes(include=np.number)

infinite_counts = np.isinf(numeric_X).sum()

print(infinite_counts[infinite_counts > 0])

Flow Bytes/s       94
Flow Packets/s    122
dtype: int64

In [22]:
non_numeric = X.select_dtypes(exclude=np.number).columns

print("Non-numeric features:")
print(non_numeric.tolist())

Non-numeric features:
[]

In [23]:
problem_cols = ["Flow Bytes/s", "Flow Packets/s"]

for col in problem_cols:
    print(f"\n===== {col} =====")

    bad_mask = X[col].isna() | np.isinf(X[col])

    print("Problematic rows:", bad_mask.sum())

    print(
        X.loc[
            bad_mask,
            [
                "Destination Port",
                "Flow Duration",
                "Total Fwd Packets",
                "Total Backward Packets",
                "Total Length of Fwd Packets",
                "Total Length of Bwd Packets",
                col
            ]
        ].head(10)
    )

===== Flow Bytes/s =====
Problematic rows: 122
       Destination Port  Flow Duration  Total Fwd Packets  \
604                1039              0                  1
3786                389              0                  2
4153              49437              0                  1
4466              35020              0                  2
4752                443              0                  1
9581              49593              0                  2
10832              9477              0                  2
11779             49634              0                  1
12504               443              0                  2
13094             49709              0                  2

       Total Backward Packets  Total Length of Fwd Packets  \
604                         1                            6
3786                        0                           39
4153                        1                            6
4466                        0                           14
4752                        1                            6
9581                        0                           75
10832                       0                            0
11779                       1                            6
12504                       0                           12
13094                       0                           12

       Total Length of Bwd Packets  Flow Bytes/s
604                              6           inf
3786                             0           inf
4153                             6           inf
4466                             0           inf
4752                             6           inf
9581                             0           inf
10832                            0           NaN
11779                            6           inf
12504                            0           inf
13094                            0           inf

===== Flow Packets/s =====
Problematic rows: 122
       Destination Port  Flow Duration  Total Fwd Packets  \
604                1039              0                  1
3786                389              0                  2
4153              49437              0                  1
4466              35020              0                  2
4752                443              0                  1
9581              49593              0                  2
10832              9477              0                  2
11779             49634              0                  1
12504               443              0                  2
13094             49709              0                  2

       Total Backward Packets  Total Length of Fwd Packets  \
604                         1                            6
3786                        0                           39
4153                        1                            6
4466                        0                           14
4752                        1                            6
9581                        0                           75
10832                       0                            0
11779                       1                            6
12504                       0                           12
13094                       0                           12

       Total Length of Bwd Packets  Flow Packets/s
604                              6             inf
3786                             0             inf
4153                             6             inf
4466                             0             inf
4752                             6             inf
9581                             0             inf
10832                            0             inf
11779                            6             inf
12504                            0             inf
13094                            0             inf

In [24]:
for col in ["Flow Bytes/s", "Flow Packets/s"]:
    print(f"\n{col}")

    print(
        X.loc[np.isinf(X[col]), col]
        .value_counts()
    )

Flow Bytes/s
Flow Bytes/s
inf    94
Name: count, dtype: int64

Flow Packets/s
Flow Packets/s
inf    122
Name: count, dtype: int64

In [25]:
for col in ["Flow Bytes/s", "Flow Packets/s"]:
    bad_mask = X[col].isna() | np.isinf(X[col])

    print(f"\n{col}")
    print(
        X.loc[
            bad_mask,
            ["Flow Duration", "Total Length of Fwd Packets",
             "Total Length of Bwd Packets",
             "Total Fwd Packets",
             "Total Backward Packets",
             col]
        ].head(20)
    )

Flow Bytes/s
       Flow Duration  Total Length of Fwd Packets  \
604                0                            6
3786               0                           39
4153               0                            6
4466               0                           14
4752               0                            6
9581               0                           75
10832              0                            0
11779              0                            6
12504              0                           12
13094              0                           12
13951              0                            6
14040              0                           12
14184              0                           12
16847              0                           37
17875              0                            6
20901              0                            0
23787              0                           31
23789              0                            0
24347              0                           12
25236              0                            6

       Total Length of Bwd Packets  Total Fwd Packets  Total Backward Packets  \
604                              6                  1                       1
3786                             0                  2                       0
4153                             6                  1                       1
4466                             0                  2                       0
4752                             6                  1                       1
9581                             0                  2                       0
10832                            0                  2                       0
11779                            6                  1                       1
12504                            0                  2                       0
13094                            0                  2                       0
13951                            6                  1                       1
14040                            0                  2                       0
14184                            0                  2                       0
16847                            0                  2                       0
17875                            6                  1                       1
20901                            0                  2                       0
23787                            0                  2                       0
23789                            0                  1                       1
24347                            0                  2                       0
25236                            6                  1                       1

       Flow Bytes/s
604             inf
3786            inf
4153            inf
4466            inf
4752            inf
9581            inf
10832           NaN
11779           inf
12504           inf
13094           inf
13951           inf
14040           inf
14184           inf
16847           inf
17875           inf
20901           NaN
23787           inf
23789           NaN
24347           inf
25236           inf

Flow Packets/s
       Flow Duration  Total Length of Fwd Packets  \
604                0                            6
3786               0                           39
4153               0                            6
4466               0                           14
4752               0                            6
9581               0                           75
10832              0                            0
11779              0                            6
12504              0                           12
13094              0                           12
13951              0                            6
14040              0                           12
14184              0                           12
16847              0                           37
17875              0                            6
20901              0                            0
23787              0                           31
23789              0                            0
24347              0                           12
25236              0                            6

       Total Length of Bwd Packets  Total Fwd Packets  Total Backward Packets  \
604                              6                  1                       1
3786                             0                  2                       0
4153                             6                  1                       1
4466                             0                  2                       0
4752                             6                  1                       1
9581                             0                  2                       0
10832                            0                  2                       0
11779                            6                  1                       1
12504                            0                  2                       0
13094                            0                  2                       0
13951                            6                  1                       1
14040                            0                  2                       0
14184                            0                  2                       0
16847                            0                  2                       0
17875                            6                  1                       1
20901                            0                  2                       0
23787                            0                  2                       0
23789                            0                  1                       1
24347                            0                  2                       0
25236                            6                  1                       1

       Flow Packets/s
604               inf
3786              inf
4153              inf
4466              inf
4752              inf
9581              inf
10832             inf
11779             inf
12504             inf
13094             inf
13951             inf
14040             inf
14184             inf
16847             inf
17875             inf
20901             inf
23787             inf
23789             inf
24347             inf
25236             inf

In [26]:
X_clean = X.copy()

In [27]:
X_clean = X_clean.replace([np.inf, -np.inf], np.nan)

In [28]:
missing_after_inf = X_clean.isnull().sum()

print(missing_after_inf[missing_after_inf > 0])

Flow Bytes/s      122
Flow Packets/s    122
dtype: int64

In [29]:
rate_columns = ["Flow Bytes/s", "Flow Packets/s"]

print(X_clean[rate_columns].median())

Flow Bytes/s      5712.358927
Flow Packets/s      98.125797
dtype: float64

In [30]:
for col in rate_columns:
    X_clean[col] = X_clean[col].fillna(X_clean[col].median())

In [31]:
print("Remaining missing values:")
print(X_clean.isnull().sum()[X_clean.isnull().sum() > 0])

print("\nRemaining infinite values:")

numeric_clean = X_clean.select_dtypes(include=np.number)

remaining_inf = np.isinf(numeric_clean).sum()

print(remaining_inf[remaining_inf > 0])

Remaining missing values:
Series([], dtype: int64)

Remaining infinite values:
Series([], dtype: int64)

In [32]:
print("Number of features:", X_clean.shape[1])

for i, col in enumerate(X_clean.columns):
    print(f"{i:2d}. {col}")

Number of features: 78
 0. Destination Port
 1. Flow Duration
 2. Total Fwd Packets
 3. Total Backward Packets
 4. Total Length of Fwd Packets
 5. Total Length of Bwd Packets
 6. Fwd Packet Length Max
 7. Fwd Packet Length Min
 8. Fwd Packet Length Mean
 9. Fwd Packet Length Std
10. Bwd Packet Length Max
11. Bwd Packet Length Min
12. Bwd Packet Length Mean
13. Bwd Packet Length Std
14. Flow Bytes/s
15. Flow Packets/s
16. Flow IAT Mean
17. Flow IAT Std
18. Flow IAT Max
19. Flow IAT Min
20. Fwd IAT Total
21. Fwd IAT Mean
22. Fwd IAT Std
23. Fwd IAT Max
24. Fwd IAT Min
25. Bwd IAT Total
26. Bwd IAT Mean
27. Bwd IAT Std
28. Bwd IAT Max
29. Bwd IAT Min
30. Fwd PSH Flags
31. Bwd PSH Flags
32. Fwd URG Flags
33. Bwd URG Flags
34. Fwd Header Length
35. Bwd Header Length
36. Fwd Packets/s
37. Bwd Packets/s
38. Min Packet Length
39. Max Packet Length
40. Packet Length Mean
41. Packet Length Std
42. Packet Length Variance
43. FIN Flag Count
44. SYN Flag Count
45. RST Flag Count
46. PSH Flag Count
47. ACK Flag Count
48. URG Flag Count
49. CWE Flag Count
50. ECE Flag Count
51. Down/Up Ratio
52. Average Packet Size
53. Avg Fwd Segment Size
54. Avg Bwd Segment Size
55. Fwd Header Length.1
56. Fwd Avg Bytes/Bulk
57. Fwd Avg Packets/Bulk
58. Fwd Avg Bulk Rate
59. Bwd Avg Bytes/Bulk
60. Bwd Avg Packets/Bulk
61. Bwd Avg Bulk Rate
62. Subflow Fwd Packets
63. Subflow Fwd Bytes
64. Subflow Bwd Packets
65. Subflow Bwd Bytes
66. Init_Win_bytes_forward
67. Init_Win_bytes_backward
68. act_data_pkt_fwd
69. min_seg_size_forward
70. Active Mean
71. Active Std
72. Active Max
73. Active Min
74. Idle Mean
75. Idle Std
76. Idle Max
77. Idle Min

In [33]:
pd.set_option("display.max_rows", 100)

feature_summary = X_clean.describe().T

print(feature_summary[["min", "max", "mean", "std"]])

                                    min           max          mean  \
Destination Port                    0.0  6.494800e+04  6.756070e+03
Flow Duration                     -12.0  1.200000e+08  1.164499e+07
Total Fwd Packets                   1.0  2.079640e+05  1.382655e+01
Total Backward Packets              0.0  2.846020e+05  1.641371e+01
Total Length of Fwd Packets         0.0  1.235152e+06  5.999468e+02
Total Length of Bwd Packets         0.0  6.270000e+08  2.838565e+04
Fwd Packet Length Max               0.0  2.482000e+04  1.747158e+02
Fwd Packet Length Min               0.0  2.325000e+03  2.389765e+01
Fwd Packet Length Mean              0.0  5.940857e+03  5.187742e+01
Fwd Packet Length Std               0.0  7.049469e+03  5.019402e+01
Bwd Packet Length Max               0.0  1.303200e+04  3.962836e+02
Bwd Packet Length Min               0.0  1.639000e+03  5.977755e+01
Bwd Packet Length Mean              0.0  3.787340e+03  1.665923e+02
Bwd Packet Length Std               0.0  2.773898e+03  1.204458e+02
Flow Bytes/s                -12000000.0  2.070000e+09  1.769952e+06
Flow Packets/s               -2000000.0  3.000000e+06  5.295018e+04
Flow IAT Mean                     -12.0  1.190000e+08  9.626813e+05
Flow IAT Std                        0.0  8.480000e+07  1.692837e+06
Flow IAT Max                      -12.0  1.200000e+08  4.602002e+06
Flow IAT Min                      -13.0  1.190000e+08  1.164674e+05
Fwd IAT Total                       0.0  1.200000e+08  1.136218e+07
Fwd IAT Mean                        0.0  1.200000e+08  2.131217e+06
Fwd IAT Std                         0.0  8.350000e+07  1.156613e+06
Fwd IAT Max                         0.0  1.200000e+08  4.455446e+06
Fwd IAT Min                         0.0  1.200000e+08  1.401511e+06
Bwd IAT Total                       0.0  1.200000e+08  1.041449e+07
Bwd IAT Mean                        0.0  1.200000e+08  2.056779e+06
Bwd IAT Std                         0.0  8.340000e+07  8.499218e+05
Bwd IAT Max                         0.0  1.200000e+08  3.705461e+06
Bwd IAT Min                         0.0  1.200000e+08  1.434653e+06
Fwd PSH Flags                       0.0  1.000000e+00  5.096502e-02
Bwd PSH Flags                       0.0  0.000000e+00  0.000000e+00
Fwd URG Flags                       0.0  0.000000e+00  0.000000e+00
Bwd URG Flags                       0.0  0.000000e+00  0.000000e+00
Fwd Header Length                   0.0  4.369484e+06  3.244953e+02
Bwd Header Length                   0.0  5.692040e+06  3.729179e+02
Fwd Packets/s                       0.0  3.000000e+06  4.746464e+04
Bwd Packets/s                       0.0  2.000000e+06  5.570105e+03
Min Packet Length                   0.0  1.359000e+03  2.314577e+01
Max Packet Length                   0.0  2.482000e+04  4.405018e+02
Packet Length Mean                  0.0  2.265586e+03  1.043719e+02
Packet Length Std                   0.0  4.708990e+03  1.310924e+02
Packet Length Variance              0.0  2.220000e+07  7.505940e+04
FIN Flag Count                      0.0  1.000000e+00  1.295064e-02
SYN Flag Count                      0.0  1.000000e+00  5.096502e-02
RST Flag Count                      0.0  1.000000e+00  2.512655e-04
PSH Flag Count                      0.0  1.000000e+00  2.266729e-01
ACK Flag Count                      0.0  1.000000e+00  2.616511e-01
URG Flag Count                      0.0  1.000000e+00  9.943832e-02
CWE Flag Count                      0.0  0.000000e+00  0.000000e+00
ECE Flag Count                      0.0  1.000000e+00  2.512655e-04
Down/Up Ratio                       0.0  8.000000e+00  6.917234e-01
Average Packet Size                 0.0  2.328000e+03  1.199769e+02
Avg Fwd Segment Size                0.0  5.940857e+03  5.187742e+01
Avg Bwd Segment Size                0.0  3.787340e+03  1.665923e+02
Fwd Header Length.1                 0.0  4.369484e+06  3.244953e+02
Fwd Avg Bytes/Bulk                  0.0  0.000000e+00  0.000000e+00
Fwd Avg Packets/Bulk                0.0  0.000000e+00  0.000000e+00
Fwd Avg Bulk Rate                   0.0  0.000000e+00  0.000000e+00
Bwd Avg Bytes/Bulk                  0.0  0.000000e+00  0.000000e+00
Bwd Avg Packets/Bulk                0.0  0.000000e+00  0.000000e+00
Bwd Avg Bulk Rate                   0.0  0.000000e+00  0.000000e+00
Subflow Fwd Packets                 1.0  2.079640e+05  1.382655e+01
Subflow Fwd Bytes                   0.0  1.235152e+06  5.999468e+02
Subflow Bwd Packets                 0.0  2.846020e+05  1.641371e+01
Subflow Bwd Bytes                   0.0  6.270395e+08  2.839081e+04
Init_Win_bytes_forward             -1.0  6.553500e+04  6.138223e+03
Init_Win_bytes_backward            -1.0  6.553500e+04  2.135183e+03
act_data_pkt_fwd                    0.0  1.986360e+05  1.032373e+01
min_seg_size_forward                0.0  5.600000e+01  2.558541e+01
Active Mean                         0.0  1.060000e+08  8.596271e+04
Active Std                          0.0  5.040000e+07  5.382912e+04
Active Max                          0.0  1.060000e+08  1.834991e+05
Active Min                          0.0  1.060000e+08  5.589691e+04
Idle Mean                           0.0  1.200000e+08  3.917041e+06
Idle Std                            0.0  7.660000e+07  1.750674e+05
Idle Max                            0.0  1.200000e+08  4.048164e+06
Idle Min                            0.0  1.200000e+08  3.745754e+06

                                      std
Destination Port             1.669744e+04
Flow Duration                3.070084e+07
Total Fwd Packets            1.097756e+03
Total Backward Packets       1.479792e+03
Total Length of Fwd Packets  7.924198e+03
Total Length of Bwd Packets  3.314538e+06
Fwd Packet Length Max        5.544752e+02
Fwd Packet Length Min        4.190994e+01
Fwd Packet Length Mean       1.170318e+02
Fwd Packet Length Std        1.604545e+02
Bwd Packet Length Max        7.948247e+02
Bwd Packet Length Min        8.097813e+01
Bwd Packet Length Mean       2.755030e+02
Bwd Packet Length Std        2.725023e+02
Flow Bytes/s                 2.463267e+07
Flow Packets/s               2.159969e+05
Flow IAT Mean                4.223484e+06
Flow IAT Std                 6.386026e+06
Flow IAT Max                 1.473038e+07
Flow IAT Min                 2.364354e+06
Fwd IAT Total                3.056995e+07
Fwd IAT Mean                 1.031844e+07
Fwd IAT Std                  4.161604e+06
Fwd IAT Max                  1.467234e+07
Fwd IAT Min                  1.008185e+07
Bwd IAT Total                2.960449e+07
Bwd IAT Mean                 1.038782e+07
Bwd IAT Std                  3.638436e+06
Bwd IAT Max                  1.359081e+07
Bwd IAT Min                  1.015369e+07
Fwd PSH Flags                2.199269e-01
Bwd PSH Flags                0.000000e+00
Fwd URG Flags                0.000000e+00
Bwd URG Flags                0.000000e+00
Fwd Header Length            2.315083e+04
Bwd Header Length            2.974892e+04
Fwd Packets/s                2.097441e+05
Bwd Packets/s                3.361726e+04
Min Packet Length            2.856880e+01
Max Packet Length            9.150019e+02
Packet Length Mean           1.614124e+02
Packet Length Std            2.405726e+02
Packet Length Variance       2.782660e+05
FIN Flag Count               1.130619e-01
SYN Flag Count               2.199269e-01
RST Flag Count               1.584941e-02
PSH Flag Count               4.186803e-01
ACK Flag Count               4.395348e-01
URG Flag Count               2.992504e-01
CWE Flag Count               0.000000e+00
ECE Flag Count               1.584941e-02
Down/Up Ratio                5.127376e-01
Average Packet Size          1.676332e+02
Avg Fwd Segment Size         1.170318e+02
Avg Bwd Segment Size         2.755030e+02
Fwd Header Length.1          2.315083e+04
Fwd Avg Bytes/Bulk           0.000000e+00
Fwd Avg Packets/Bulk         0.000000e+00
Fwd Avg Bulk Rate            0.000000e+00
Bwd Avg Bytes/Bulk           0.000000e+00
Bwd Avg Packets/Bulk         0.000000e+00
Bwd Avg Bulk Rate            0.000000e+00
Subflow Fwd Packets          1.097756e+03
Subflow Fwd Bytes            7.924198e+03
Subflow Bwd Packets          1.479792e+03
Subflow Bwd Bytes            3.315178e+06
Init_Win_bytes_forward       1.381445e+04
Init_Win_bytes_backward      9.243553e+03
act_data_pkt_fwd             1.046038e+03
min_seg_size_forward         6.380665e+00
Active Mean                  8.681320e+05
Active Std                   4.929487e+05
Active Max                   1.333719e+06
Active Min                   7.628561e+05
Idle Mean                    1.388267e+07
Idle Std                     2.167443e+06
Idle Max                     1.424123e+07
Idle Min                     1.370477e+07

In [34]:
print(y.value_counts())
print("\nPercentages:")
print(y.value_counts(normalize=True) * 100)

Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

Percentages:
Label
BENIGN    98.970858
Bot        1.029142
Name: proportion, dtype: float64

In [35]:
negative_cols = [
    "Flow Duration",
    "Flow IAT Mean",
    "Flow IAT Max",
    "Flow IAT Min",
    "Flow Bytes/s",
    "Flow Packets/s"
]

for col in negative_cols:
    negative_rows = X_clean[X_clean[col] < 0]

    print(f"\n{col}")
    print("Negative values:", len(negative_rows))

    if len(negative_rows) > 0:
        print(negative_rows[[col, "Destination Port", "Total Fwd Packets",
                             "Total Backward Packets"]].head())

Flow Duration
Negative values: 9
       Flow Duration  Destination Port  Total Fwd Packets  \
17562             -1                80                  1
45711             -1                80                  1
64028             -1               443                  1
73453            -12                80                  1
85150             -1               443                  1

       Total Backward Packets
17562                       1
45711                       1
64028                       1
73453                       1
85150                       1

Flow IAT Mean
Negative values: 9
       Flow IAT Mean  Destination Port  Total Fwd Packets  \
17562           -1.0                80                  1
45711           -1.0                80                  1
64028           -1.0               443                  1
73453          -12.0                80                  1
85150           -1.0               443                  1

       Total Backward Packets
17562                       1
45711                       1
64028                       1
73453                       1
85150                       1

Flow IAT Max
Negative values: 9
       Flow IAT Max  Destination Port  Total Fwd Packets  \
17562            -1                80                  1
45711            -1                80                  1
64028            -1               443                  1
73453           -12                80                  1
85150            -1               443                  1

       Total Backward Packets
17562                       1
45711                       1
64028                       1
73453                       1
85150                       1

Flow IAT Min
Negative values: 225
      Flow IAT Min  Destination Port  Total Fwd Packets  \
688             -1                80                156
703             -1               443               1161
860             -1                80               3694
1605            -1               443               1303
2125           -13               443                 24

      Total Backward Packets
688                      181
703                     1802
860                     4673
1605                    2363
2125                      20

Flow Bytes/s
Negative values: 8
        Flow Bytes/s  Destination Port  Total Fwd Packets  \
45711    -12000000.0                80                  1
64028    -12000000.0               443                  1
73453     -1000000.0                80                  1
85150    -12000000.0               443                  1
113821   -12000000.0               443                  1

        Total Backward Packets
45711                        1
64028                        1
73453                        1
85150                        1
113821                       1

Flow Packets/s
Negative values: 9
       Flow Packets/s  Destination Port  Total Fwd Packets  \
17562   -2.000000e+06                80                  1
45711   -2.000000e+06                80                  1
64028   -2.000000e+06               443                  1
73453   -1.666667e+05                80                  1
85150   -2.000000e+06               443                  1

       Total Backward Packets
17562                       1
45711                       1
64028                       1
73453                       1
85150                       1

In [36]:
problem_columns = [
    "Flow Duration",
    "Flow IAT Mean",
    "Flow IAT Max",
    "Flow IAT Min",
    "Flow Bytes/s",
    "Flow Packets/s"
]

for col in problem_columns:
    count = (X_clean[col] < 0).sum()
    print(f"{col}: {count}")

Flow Duration: 9
Flow IAT Mean: 9
Flow IAT Max: 9
Flow IAT Min: 225
Flow Bytes/s: 8
Flow Packets/s: 9

In [37]:
negative_mask = (X_clean[problem_columns] < 0).any(axis=1)

print("Rows containing at least one negative value:",
      negative_mask.sum())

Rows containing at least one negative value: 225

In [38]:
X_final = X_clean.copy()

negative_to_nan = [
    "Flow Duration",
    "Flow IAT Mean",
    "Flow IAT Max",
    "Flow IAT Min",
    "Flow Bytes/s",
    "Flow Packets/s"
]

for col in negative_to_nan:
    X_final.loc[X_final[col] < 0, col] = np.nan

In [39]:
missing_final = X_final.isnull().sum()

print(missing_final[missing_final > 0])

Flow Duration       9
Flow Bytes/s        8
Flow Packets/s      9
Flow IAT Mean       9
Flow IAT Max        9
Flow IAT Min      225
dtype: int64

In [40]:
for col in negative_to_nan:
    median_value = X_final[col].median()
    X_final[col] = X_final[col].fillna(median_value)

In [41]:
print("Remaining missing values:")
print(X_final.isnull().sum()[X_final.isnull().sum() > 0])

print("\nRemaining infinite values:")

numeric_final = X_final.select_dtypes(include=np.number)
remaining_inf = np.isinf(numeric_final).sum()

print(remaining_inf[remaining_inf > 0])

print("\nRemaining negative values in checked columns:")

for col in negative_to_nan:
    print(col, (X_final[col] < 0).sum())

Remaining missing values:
Series([], dtype: int64)

Remaining infinite values:
Series([], dtype: int64)

Remaining negative values in checked columns:
Flow Duration 0
Flow IAT Mean 0
Flow IAT Max 0
Flow IAT Min 0
Flow Bytes/s 0
Flow Packets/s 0

In [42]:
sample_alert = X_final.iloc[0].to_dict()

print(sample_alert)

{'Destination Port': 3268.0, 'Flow Duration': 112740690.0, 'Total Fwd Packets': 32.0, 'Total Backward Packets': 16.0, 'Total Length of Fwd Packets': 6448.0, 'Total Length of Bwd Packets': 1152.0, 'Fwd Packet Length Max': 403.0, 'Fwd Packet Length Min': 0.0, 'Fwd Packet Length Mean': 201.5, 'Fwd Packet Length Std': 204.7242047, 'Bwd Packet Length Max': 72.0, 'Bwd Packet Length Min': 72.0, 'Bwd Packet Length Mean': 72.0, 'Bwd Packet Length Std': 0.0, 'Flow Bytes/s': 67.41133126, 'Flow Packets/s': 0.425755776, 'Flow IAT Mean': 2398738.085, 'Flow IAT Std': 5798697.94, 'Flow IAT Max': 16400000.0, 'Flow IAT Min': 3.0, 'Fwd IAT Total': 113000000.0, 'Fwd IAT Mean': 3636796.452, 'Fwd IAT Std': 6848760.823, 'Fwd IAT Max': 16400000.0, 'Fwd IAT Min': 3.0, 'Bwd IAT Total': 113000000.0, 'Bwd IAT Mean': 7516023.2, 'Bwd IAT Std': 8323384.915, 'Bwd IAT Max': 16400000.0, 'Bwd IAT Min': 3.0, 'Fwd PSH Flags': 1.0, 'Bwd PSH Flags': 0.0, 'Fwd URG Flags': 0.0, 'Bwd URG Flags': 0.0, 'Fwd Header Length': 1024.0, 'Bwd Header Length': 512.0, 'Fwd Packets/s': 0.283837184, 'Bwd Packets/s': 0.141918592, 'Min Packet Length': 0.0, 'Max Packet Length': 403.0, 'Packet Length Mean': 163.3265306, 'Packet Length Std': 178.9317127, 'Packet Length Variance': 32016.55782, 'FIN Flag Count': 0.0, 'SYN Flag Count': 1.0, 'RST Flag Count': 0.0, 'PSH Flag Count': 0.0, 'ACK Flag Count': 1.0, 'URG Flag Count': 0.0, 'CWE Flag Count': 0.0, 'ECE Flag Count': 0.0, 'Down/Up Ratio': 0.0, 'Average Packet Size': 166.7291667, 'Avg Fwd Segment Size': 201.5, 'Avg Bwd Segment Size': 72.0, 'Fwd Header Length.1': 1024.0, 'Fwd Avg Bytes/Bulk': 0.0, 'Fwd Avg Packets/Bulk': 0.0, 'Fwd Avg Bulk Rate': 0.0, 'Bwd Avg Bytes/Bulk': 0.0, 'Bwd Avg Packets/Bulk': 0.0, 'Bwd Avg Bulk Rate': 0.0, 'Subflow Fwd Packets': 32.0, 'Subflow Fwd Bytes': 6448.0, 'Subflow Bwd Packets': 16.0, 'Subflow Bwd Bytes': 1152.0, 'Init_Win_bytes_forward': 377.0, 'Init_Win_bytes_backward': 2079.0, 'act_data_pkt_fwd': 15.0, 'min_seg_size_forward': 32.0, 'Active Mean': 359.4285714, 'Active Std': 11.99801571, 'Active Max': 380.0, 'Active Min': 343.0, 'Idle Mean': 16100000.0, 'Idle Std': 498804.8203, 'Idle Max': 16400000.0, 'Idle Min': 15400000.0}

In [43]:
def create_soc_alert(row, alert_id):
    return {
        "alert_id": alert_id,

        "service": {
            "destination_port": row["Destination Port"]
        },

        "flow": {
            "duration": row["Flow Duration"],
            "forward_packets": row["Total Fwd Packets"],
            "backward_packets": row["Total Backward Packets"],
            "forward_bytes": row["Total Length of Fwd Packets"],
            "backward_bytes": row["Total Length of Bwd Packets"]
        },

        "traffic": {
            "bytes_per_second": row["Flow Bytes/s"],
            "packets_per_second": row["Flow Packets/s"],
            "forward_packets_per_second": row["Fwd Packets/s"],
            "backward_packets_per_second": row["Bwd Packets/s"]
        },

        "packet_characteristics": {
            "forward_length_mean": row["Fwd Packet Length Mean"],
            "backward_length_mean": row["Bwd Packet Length Mean"],
            "packet_length_mean": row["Packet Length Mean"],
            "packet_length_std": row["Packet Length Std"]
        },

        "timing": {
            "flow_iat_mean": row["Flow IAT Mean"],
            "flow_iat_std": row["Flow IAT Std"],
            "flow_iat_max": row["Flow IAT Max"],
            "flow_iat_min": row["Flow IAT Min"]
        },

        "tcp_flags": {
            "fin": row["FIN Flag Count"],
            "syn": row["SYN Flag Count"],
            "rst": row["RST Flag Count"],
            "psh": row["PSH Flag Count"],
            "ack": row["ACK Flag Count"],
            "urg": row["URG Flag Count"]
        },

        "connection": {
            "init_window_forward": row["Init_Win_bytes_forward"],
            "init_window_backward": row["Init_Win_bytes_backward"],
            "active_mean": row["Active Mean"],
            "idle_mean": row["Idle Mean"]
        },

        "raw_features": row.to_dict()
    }

In [44]:
sample_alert = create_soc_alert(
    X_final.iloc[0],
    "ALERT_0001"
)

sample_alert

{'alert_id': 'ALERT_0001',
 'service': {'destination_port': np.float64(3268.0)},
 'flow': {'duration': np.float64(112740690.0),
  'forward_packets': np.float64(32.0),
  'backward_packets': np.float64(16.0),
  'forward_bytes': np.float64(6448.0),
  'backward_bytes': np.float64(1152.0)},
 'traffic': {'bytes_per_second': np.float64(67.41133126),
  'packets_per_second': np.float64(0.425755776),
  'forward_packets_per_second': np.float64(0.283837184),
  'backward_packets_per_second': np.float64(0.141918592)},
 'packet_characteristics': {'forward_length_mean': np.float64(201.5),
  'backward_length_mean': np.float64(72.0),
  'packet_length_mean': np.float64(163.3265306),
  'packet_length_std': np.float64(178.9317127)},
 'timing': {'flow_iat_mean': np.float64(2398738.085),
  'flow_iat_std': np.float64(5798697.94),
  'flow_iat_max': np.float64(16400000.0),
  'flow_iat_min': np.float64(3.0)},
 'tcp_flags': {'fin': np.float64(0.0),
  'syn': np.float64(1.0),
  'rst': np.float64(0.0),
  'psh': np.float64(0.0),
  'ack': np.float64(1.0),
  'urg': np.float64(0.0)},
 'connection': {'init_window_forward': np.float64(377.0),
  'init_window_backward': np.float64(2079.0),
  'active_mean': np.float64(359.4285714),
  'idle_mean': np.float64(16100000.0)},
 'raw_features': {'Destination Port': 3268.0,
  'Flow Duration': 112740690.0,
  'Total Fwd Packets': 32.0,
  'Total Backward Packets': 16.0,
  'Total Length of Fwd Packets': 6448.0,
  'Total Length of Bwd Packets': 1152.0,
  'Fwd Packet Length Max': 403.0,
  'Fwd Packet Length Min': 0.0,
  'Fwd Packet Length Mean': 201.5,
  'Fwd Packet Length Std': 204.7242047,
  'Bwd Packet Length Max': 72.0,
  'Bwd Packet Length Min': 72.0,
  'Bwd Packet Length Mean': 72.0,
  'Bwd Packet Length Std': 0.0,
  'Flow Bytes/s': 67.41133126,
  'Flow Packets/s': 0.425755776,
  'Flow IAT Mean': 2398738.085,
  'Flow IAT Std': 5798697.94,
  'Flow IAT Max': 16400000.0,
  'Flow IAT Min': 3.0,
  'Fwd IAT Total': 113000000.0,
  'Fwd IAT Mean': 3636796.452,
  'Fwd IAT Std': 6848760.823,
  'Fwd IAT Max': 16400000.0,
  'Fwd IAT Min': 3.0,
  'Bwd IAT Total': 113000000.0,
  'Bwd IAT Mean': 7516023.2,
  'Bwd IAT Std': 8323384.915,
  'Bwd IAT Max': 16400000.0,
  'Bwd IAT Min': 3.0,
  'Fwd PSH Flags': 1.0,
  'Bwd PSH Flags': 0.0,
  'Fwd URG Flags': 0.0,
  'Bwd URG Flags': 0.0,
  'Fwd Header Length': 1024.0,
  'Bwd Header Length': 512.0,
  'Fwd Packets/s': 0.283837184,
  'Bwd Packets/s': 0.141918592,
  'Min Packet Length': 0.0,
  'Max Packet Length': 403.0,
  'Packet Length Mean': 163.3265306,
  'Packet Length Std': 178.9317127,
  'Packet Length Variance': 32016.55782,
  'FIN Flag Count': 0.0,
  'SYN Flag Count': 1.0,
  'RST Flag Count': 0.0,
  'PSH Flag Count': 0.0,
  'ACK Flag Count': 1.0,
  'URG Flag Count': 0.0,
  'CWE Flag Count': 0.0,
  'ECE Flag Count': 0.0,
  'Down/Up Ratio': 0.0,
  'Average Packet Size': 166.7291667,
  'Avg Fwd Segment Size': 201.5,
  'Avg Bwd Segment Size': 72.0,
  'Fwd Header Length.1': 1024.0,
  'Fwd Avg Bytes/Bulk': 0.0,
  'Fwd Avg Packets/Bulk': 0.0,
  'Fwd Avg Bulk Rate': 0.0,
  'Bwd Avg Bytes/Bulk': 0.0,
  'Bwd Avg Packets/Bulk': 0.0,
  'Bwd Avg Bulk Rate': 0.0,
  'Subflow Fwd Packets': 32.0,
  'Subflow Fwd Bytes': 6448.0,
  'Subflow Bwd Packets': 16.0,
  'Subflow Bwd Bytes': 1152.0,
  'Init_Win_bytes_forward': 377.0,
  'Init_Win_bytes_backward': 2079.0,
  'act_data_pkt_fwd': 15.0,
  'min_seg_size_forward': 32.0,
  'Active Mean': 359.4285714,
  'Active Std': 11.99801571,
  'Active Max': 380.0,
  'Active Min': 343.0,
  'Idle Mean': 16100000.0,
  'Idle Std': 498804.8203,
  'Idle Max': 16400000.0,
  'Idle Min': 15400000.0}}

In [45]:
alerts = []

for i in range(10):
    alert = create_soc_alert(
        X_final.iloc[i],
        f"ALERT_{i+1:04d}"
    )
    alerts.append(alert)

print(f"Generated {len(alerts)} alerts.")

Generated 10 alerts.

In [46]:
for alert in alerts:
    print(alert["alert_id"])

ALERT_0001
ALERT_0002
ALERT_0003
ALERT_0004
ALERT_0005
ALERT_0006
ALERT_0007
ALERT_0008
ALERT_0009
ALERT_0010

In [47]:
print("Label" in alerts[0]["raw_features"])

False

In [48]:
print("Label" in alerts[0])

False

In [49]:
for alert in alerts:
    missing_values = []

    for section_name, section in alert.items():
        if isinstance(section, dict):
            for key, value in section.items():
                if pd.isna(value):
                    missing_values.append((section_name, key))

    if missing_values:
        print(alert["alert_id"], missing_values)

In [50]:
for key, value in alerts[0].items():
    if key != "raw_features":
        print(key, ":", value)

alert_id : ALERT_0001
service : {'destination_port': np.float64(3268.0)}
flow : {'duration': np.float64(112740690.0), 'forward_packets': np.float64(32.0), 'backward_packets': np.float64(16.0), 'forward_bytes': np.float64(6448.0), 'backward_bytes': np.float64(1152.0)}
traffic : {'bytes_per_second': np.float64(67.41133126), 'packets_per_second': np.float64(0.425755776), 'forward_packets_per_second': np.float64(0.283837184), 'backward_packets_per_second': np.float64(0.141918592)}
packet_characteristics : {'forward_length_mean': np.float64(201.5), 'backward_length_mean': np.float64(72.0), 'packet_length_mean': np.float64(163.3265306), 'packet_length_std': np.float64(178.9317127)}
timing : {'flow_iat_mean': np.float64(2398738.085), 'flow_iat_std': np.float64(5798697.94), 'flow_iat_max': np.float64(16400000.0), 'flow_iat_min': np.float64(3.0)}
tcp_flags : {'fin': np.float64(0.0), 'syn': np.float64(1.0), 'rst': np.float64(0.0), 'psh': np.float64(0.0), 'ack': np.float64(1.0), 'urg': np.float64(0.0)}
connection : {'init_window_forward': np.float64(377.0), 'init_window_backward': np.float64(2079.0), 'active_mean': np.float64(359.4285714), 'idle_mean': np.float64(16100000.0)}

In [51]:
import os

knowledge_base_path = "/home/jupyter-itproject2026/TrustSOC/data/knowledge_base"

print(os.listdir(knowledge_base_path))

[]

In [52]:
import os
import requests

knowledge_base_path = "/home/jupyter-itproject2026/TrustSOC/data/knowledge_base"
mitre_path = os.path.join(knowledge_base_path, "mitre_attack")

os.makedirs(mitre_path, exist_ok=True)

url = "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack.json"

response = requests.get(url)
response.raise_for_status()

file_path = os.path.join(mitre_path, "enterprise-attack.json")

with open(file_path, "wb") as f:
    f.write(response.content)

print("MITRE ATT&CK downloaded successfully.")
print("Saved to:", file_path)
print("File size:", round(os.path.getsize(file_path) / (1024 * 1024), 2), "MB")

MITRE ATT&CK downloaded successfully.
Saved to: /home/jupyter-itproject2026/TrustSOC/data/knowledge_base/mitre_attack/enterprise-attack.json
File size: 51.34 MB

In [53]:
print(os.listdir(mitre_path))

['enterprise-attack.json']

In [54]:
import json

with open(file_path, "r", encoding="utf-8") as f:
    attack_data = json.load(f)

print(type(attack_data))
print(attack_data.keys())

<class 'dict'>
dict_keys(['type', 'id', 'objects'])

In [55]:
from collections import Counter

object_types = Counter(
    obj.get("type")
    for obj in attack_data["objects"]
)

print(object_types)

Counter({'relationship': 21262, 'x-mitre-analytic': 1758, 'attack-pattern': 858, 'malware': 733, 'x-mitre-detection-strategy': 699, 'course-of-action': 268, 'intrusion-set': 191, 'x-mitre-data-component': 109, 'tool': 95, 'campaign': 56, 'x-mitre-data-source': 38, 'x-mitre-tactic': 15, 'x-mitre-collection': 1, 'x-mitre-matrix': 1, 'identity': 1, 'marking-definition': 1})

In [56]:
print("Total ATT&CK objects:", len(attack_data["objects"]))

Total ATT&CK objects: 26086

In [57]:
for obj in attack_data["objects"][:3]:
    print(obj["type"])
    print(obj.get("name"))
    print()

x-mitre-collection
Enterprise ATT&CK

campaign
Operation Dream Job

campaign
KV Botnet Activity

In [58]:
attack_patterns = [
    obj for obj in attack_data["objects"]
    if obj.get("type") == "attack-pattern"
]

print("Attack patterns:", len(attack_patterns))

example = attack_patterns[0]

print(example.keys())

Attack patterns: 858
dict_keys(['type', 'spec_version', 'id', 'created', 'created_by_ref', 'revoked', 'external_references', 'object_marking_refs', 'modified', 'name', 'description', 'kill_chain_phases', 'x_mitre_attack_spec_version', 'x_mitre_deprecated', 'x_mitre_domains', 'x_mitre_is_subtechnique', 'x_mitre_modified_by_ref', 'x_mitre_platforms', 'x_mitre_version'])

In [59]:
print("Name:", example.get("name"))
print("Description:", example.get("description"))
print("External references:", example.get("external_references"))

Name: Extra Window Memory Injection
Description: Adversaries may inject malicious code into process via Extra Window Memory (EWM) in order to evade process-based defenses as well as possibly elevate privileges. EWM injection is a method of executing arbitrary code in the address space of a separate live process.

Before creating a window, graphical Windows-based processes must prescribe to or register a windows class, which stipulate appearance and behavior (via windows procedures, which are functions that handle input/output of data).(Citation: Microsoft Window Classes) Registration of new windows classes can include a request for up to 40 bytes of EWM to be appended to the allocated memory of each instance of that class. This EWM is intended to store data specific to that window and has specific application programming interface (API) functions to set and get its value. (Citation: Microsoft GetWindowLong function) (Citation: Microsoft SetWindowLong function)

Although small, the EWM is large enough to store a 32-bit pointer and is often used to point to a windows procedure. Malware may possibly utilize this memory location in part of an attack chain that includes writing code to shared sections of the process’s memory, placing a pointer to the code in EWM, then invoking execution by returning execution control to the address in the process’s EWM.

Execution granted through EWM injection may allow access to both the target process's memory and possibly elevated privileges. Writing payloads to shared sections also avoids the use of highly monitored API calls such as <code>WriteProcessMemory</code> and <code>CreateRemoteThread</code>.(Citation: Elastic Process Injection July 2017) More sophisticated malware samples may also potentially bypass protection mechanisms such as data execution prevention (DEP) by triggering a combination of windows procedures and other system functions that will rewrite the malicious payload inside an executable portion of the target process.  (Citation: MalwareTech Power Loader Aug 2013) (Citation: WeLiveSecurity Gapz and Redyms Mar 2013)

Running code in the context of another process may allow access to the process's memory, system/network resources, and possibly elevated privileges. Execution via EWM injection may also evade detection from security products since the execution is masked under a legitimate process.
External references: [{'source_name': 'mitre-attack', 'url': 'https://attack.mitre.org/techniques/T1055/011', 'external_id': 'T1055.011'}, {'source_name': 'Elastic Process Injection July 2017', 'description': 'Hosseini, A. (2017, July 18). Ten Process Injection Techniques: A Technical Survey Of Common And Trending Process Injection Techniques. Retrieved December 7, 2017.', 'url': 'https://www.endgame.com/blog/technical-blog/ten-process-injection-techniques-technical-survey-common-and-trending-process'}, {'source_name': 'MalwareTech Power Loader Aug 2013', 'description': 'MalwareTech. (2013, August 13). PowerLoader Injection – Something truly amazing. Retrieved December 16, 2017.', 'url': 'https://www.malwaretech.com/2013/08/powerloader-injection-something-truly.html'}, {'source_name': 'WeLiveSecurity Gapz and Redyms Mar 2013', 'description': 'Matrosov, A. (2013, March 19). Gapz and Redyms droppers based on Power Loader code. Retrieved December 16, 2017.', 'url': 'https://www.welivesecurity.com/2013/03/19/gapz-and-redyms-droppers-based-on-power-loader-code/'}, {'source_name': 'Microsoft Window Classes', 'description': 'Microsoft. (n.d.). About Window Classes. Retrieved December 16, 2017.', 'url': 'https://msdn.microsoft.com/library/windows/desktop/ms633574.aspx'}, {'source_name': 'Microsoft GetWindowLong function', 'description': 'Microsoft. (n.d.). GetWindowLong function. Retrieved December 16, 2017.', 'url': 'https://msdn.microsoft.com/library/windows/desktop/ms633584.aspx'}, {'source_name': 'Microsoft SetWindowLong function', 'description': 'Microsoft. (n.d.). SetWindowLong function. Retrieved December 16, 2017.', 'url': 'https://msdn.microsoft.com/library/windows/desktop/ms633591.aspx'}]

In [60]:
print("Kill chain phases:")
for phase in example.get("kill_chain_phases", []):
    print(phase)

Kill chain phases:
{'kill_chain_name': 'mitre-attack', 'phase_name': 'stealth'}
{'kill_chain_name': 'mitre-attack', 'phase_name': 'privilege-escalation'}

In [61]:
print("Platforms:", example.get("x_mitre_platforms"))

Platforms: ['Windows']

In [62]:
print("Is sub-technique:", example.get("x_mitre_is_subtechnique"))

Is sub-technique: True

In [63]:
def extract_attack_patterns(attack_data):
    documents = []

    for obj in attack_data["objects"]:

        if obj.get("type") != "attack-pattern":
            continue

        if obj.get("revoked") or obj.get("x_mitre_deprecated"):
            continue

        technique_name = obj.get("name", "")
        description = obj.get("description", "")

        technique_id = None

        for reference in obj.get("external_references", []):
            if reference.get("source_name") == "mitre-attack":
                technique_id = reference.get("external_id")
                break

        tactics = []

        for phase in obj.get("kill_chain_phases", []):
            if phase.get("kill_chain_name") == "mitre-attack":
                tactics.append(phase.get("phase_name"))

        platforms = obj.get("x_mitre_platforms", [])

        document = {
            "source": "MITRE ATT&CK",
            "type": "attack-pattern",
            "name": technique_name,
            "technique_id": technique_id,
            "description": description,
            "tactics": tactics,
            "platforms": platforms,
            "is_subtechnique": obj.get("x_mitre_is_subtechnique", False)
        }

        documents.append(document)

    return documents

In [64]:
mitre_documents = extract_attack_patterns(attack_data)

print("Extracted documents:", len(mitre_documents))

Extracted documents: 697

In [65]:
print(mitre_documents[0])

{'source': 'MITRE ATT&CK', 'type': 'attack-pattern', 'name': 'Extra Window Memory Injection', 'technique_id': 'T1055.011', 'description': "Adversaries may inject malicious code into process via Extra Window Memory (EWM) in order to evade process-based defenses as well as possibly elevate privileges. EWM injection is a method of executing arbitrary code in the address space of a separate live process. \n\nBefore creating a window, graphical Windows-based processes must prescribe to or register a windows class, which stipulate appearance and behavior (via windows procedures, which are functions that handle input/output of data).(Citation: Microsoft Window Classes) Registration of new windows classes can include a request for up to 40 bytes of EWM to be appended to the allocated memory of each instance of that class. This EWM is intended to store data specific to that window and has specific application programming interface (API) functions to set and get its value. (Citation: Microsoft GetWindowLong function) (Citation: Microsoft SetWindowLong function)\n\nAlthough small, the EWM is large enough to store a 32-bit pointer and is often used to point to a windows procedure. Malware may possibly utilize this memory location in part of an attack chain that includes writing code to shared sections of the process’s memory, placing a pointer to the code in EWM, then invoking execution by returning execution control to the address in the process’s EWM.\n\nExecution granted through EWM injection may allow access to both the target process's memory and possibly elevated privileges. Writing payloads to shared sections also avoids the use of highly monitored API calls such as <code>WriteProcessMemory</code> and <code>CreateRemoteThread</code>.(Citation: Elastic Process Injection July 2017) More sophisticated malware samples may also potentially bypass protection mechanisms such as data execution prevention (DEP) by triggering a combination of windows procedures and other system functions that will rewrite the malicious payload inside an executable portion of the target process.  (Citation: MalwareTech Power Loader Aug 2013) (Citation: WeLiveSecurity Gapz and Redyms Mar 2013)\n\nRunning code in the context of another process may allow access to the process's memory, system/network resources, and possibly elevated privileges. Execution via EWM injection may also evade detection from security products since the execution is masked under a legitimate process. ", 'tactics': ['stealth', 'privilege-escalation'], 'platforms': ['Windows'], 'is_subtechnique': True}

In [66]:
print("Keys:", mitre_documents[0].keys())

Keys: dict_keys(['source', 'type', 'name', 'technique_id', 'description', 'tactics', 'platforms', 'is_subtechnique'])

In [67]:
subtechnique_count = sum(
    doc["is_subtechnique"]
    for doc in mitre_documents
)

print("Sub-techniques:", subtechnique_count)
print("Techniques / parent techniques:", len(mitre_documents) - subtechnique_count)

Sub-techniques: 475
Techniques / parent techniques: 222

In [68]:
def create_mitre_text(document):
    tactics = ", ".join(document["tactics"])
    platforms = ", ".join(document["platforms"])

    text = f"""
Source: {document["source"]}
Type: {document["type"]}
Technique: {document["name"]}
Technique ID: {document["technique_id"]}

Description:
{document["description"]}

Tactics:
{tactics}

Platforms:
{platforms}

Sub-technique:
{document["is_subtechnique"]}
""".strip()

    return text

In [69]:
mitre_documents[0]["text"] = create_mitre_text(mitre_documents[0])

print(mitre_documents[0]["text"])

Source: MITRE ATT&CK
Type: attack-pattern
Technique: Extra Window Memory Injection
Technique ID: T1055.011

Description:
Adversaries may inject malicious code into process via Extra Window Memory (EWM) in order to evade process-based defenses as well as possibly elevate privileges. EWM injection is a method of executing arbitrary code in the address space of a separate live process.

Before creating a window, graphical Windows-based processes must prescribe to or register a windows class, which stipulate appearance and behavior (via windows procedures, which are functions that handle input/output of data).(Citation: Microsoft Window Classes) Registration of new windows classes can include a request for up to 40 bytes of EWM to be appended to the allocated memory of each instance of that class. This EWM is intended to store data specific to that window and has specific application programming interface (API) functions to set and get its value. (Citation: Microsoft GetWindowLong function) (Citation: Microsoft SetWindowLong function)

Although small, the EWM is large enough to store a 32-bit pointer and is often used to point to a windows procedure. Malware may possibly utilize this memory location in part of an attack chain that includes writing code to shared sections of the process’s memory, placing a pointer to the code in EWM, then invoking execution by returning execution control to the address in the process’s EWM.

Execution granted through EWM injection may allow access to both the target process's memory and possibly elevated privileges. Writing payloads to shared sections also avoids the use of highly monitored API calls such as <code>WriteProcessMemory</code> and <code>CreateRemoteThread</code>.(Citation: Elastic Process Injection July 2017) More sophisticated malware samples may also potentially bypass protection mechanisms such as data execution prevention (DEP) by triggering a combination of windows procedures and other system functions that will rewrite the malicious payload inside an executable portion of the target process.  (Citation: MalwareTech Power Loader Aug 2013) (Citation: WeLiveSecurity Gapz and Redyms Mar 2013)

Running code in the context of another process may allow access to the process's memory, system/network resources, and possibly elevated privileges. Execution via EWM injection may also evade detection from security products since the execution is masked under a legitimate process.

Tactics:
stealth, privilege-escalation

Platforms:
Windows

Sub-technique:
True

In [70]:
for document in mitre_documents:
    document["text"] = create_mitre_text(document)

print("Documents ready for embedding:", len(mitre_documents))

Documents ready for embedding: 697

In [71]:
print(mitre_documents[10]["text"])

Source: MITRE ATT&CK
Type: attack-pattern
Technique: Adversary-in-the-Middle
Technique ID: T1557

Description:
Adversaries may attempt to position themselves between two or more networked devices using an adversary-in-the-middle (AiTM) technique to support follow-on behaviors such as [Network Sniffing](https://attack.mitre.org/techniques/T1040), [Transmitted Data Manipulation](https://attack.mitre.org/techniques/T1565/002), or replay attacks ([Exploitation for Credential Access](https://attack.mitre.org/techniques/T1212)). By abusing features of common networking protocols that can determine the flow of network traffic (e.g. ARP, DNS, LLMNR, etc.), adversaries may force a device to communicate through an adversary controlled system so they can collect information or perform additional actions.(Citation: Rapid7 MiTM Basics)

For example, adversaries may manipulate victim DNS settings to enable other malicious activities such as preventing/redirecting users from accessing legitimate sites and/or pushing additional malware.(Citation: ttint_rat)(Citation: dns_changer_trojans)(Citation: ad_blocker_with_miner) Adversaries may also manipulate DNS and leverage their position in order to intercept user credentials, including access tokens ([Steal Application Access Token](https://attack.mitre.org/techniques/T1528)) and session cookies ([Steal Web Session Cookie](https://attack.mitre.org/techniques/T1539)).(Citation: volexity_0day_sophos_FW)(Citation: Token tactics) [Downgrade Attack](https://attack.mitre.org/techniques/T1689)s can also be used to establish an AiTM position, such as by negotiating a less secure, deprecated, or weaker version of communication protocol (SSL/TLS) or encryption algorithm.(Citation: mitm_tls_downgrade_att)(Citation: taxonomy_downgrade_att_tls)(Citation: tlseminar_downgrade_att)

Adversaries may also leverage the AiTM position to attempt to monitor and/or modify traffic, such as in [Transmitted Data Manipulation](https://attack.mitre.org/techniques/T1565/002). Adversaries can setup a position similar to AiTM to prevent traffic from flowing to the appropriate destination, potentially to impair defenses and/or in support of a [Network Denial of Service](https://attack.mitre.org/techniques/T1498).

Tactics:
credential-access, collection

Platforms:
Linux, macOS, Network Devices, Windows

Sub-technique:
False

In [72]:
import json
import os

processed_file = os.path.join(
    mitre_path,
    "mitre_attack_documents.json"
)

with open(processed_file, "w", encoding="utf-8") as f:
    json.dump(
        mitre_documents,
        f,
        indent=2,
        ensure_ascii=False
    )

print("Processed MITRE corpus saved.")
print("Path:", processed_file)
print(
    "Size:",
    round(os.path.getsize(processed_file) / (1024 * 1024), 2),
    "MB"
)

Processed MITRE corpus saved.
Path: /home/jupyter-itproject2026/TrustSOC/data/knowledge_base/mitre_attack/mitre_attack_documents.json
Size: 2.23 MB

In [73]:
print(os.listdir(mitre_path))

['enterprise-attack.json', 'mitre_attack_documents.json']

In [74]:
import importlib.util

packages = [
    "sentence_transformers",
    "faiss",
    "chromadb",
    "langchain",
    "langchain_community"
]

for package in packages:
    installed = importlib.util.find_spec(package) is not None
    print(f"{package}: {'installed' if installed else 'not installed'}")

sentence_transformers: not installed
faiss: not installed
chromadb: not installed
langchain: not installed
langchain_community: not installed

In [75]:
!pip install sentence-transformers faiss-cpu

Defaulting to user installation because normal site-packages is not writeable
Collecting sentence-transformers
  Downloading sentence_transformers-6.1.0-py3-none-any.whl.metadata (20 kB)
Collecting faiss-cpu
  Downloading faiss_cpu-1.15.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Collecting transformers<6.0.0,>=5.0.0 (from sentence-transformers)
  Downloading transformers-5.17.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: tokenizers>=0.19 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (0.20.3)
Collecting huggingface-hub<2.0.0,>=1.3.0 (from sentence-transformers)
  Downloading huggingface_hub-1.32.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: torch>=2.2 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (2.5.1+cu121)
Requirement already satisfied: numpy>=1.24.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (2.4.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.10.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from faiss-cpu) (26.0)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers)
  Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/tljh/user/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.4.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
INFO: pip is looking at multiple versions of tokenizers to determine which version is compatible with other requirements. This could take a while.
Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: networkx in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (3.1.0)
Requirement already satisfied: setuptools in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (70.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.2->sentence-transformers) (12.9.86)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from sympy==1.13.1->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: regex>=2025.10.22 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: typer in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.24.1)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: anyio in /opt/tljh/user/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.12.0)
Requirement already satisfied: certifi in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /opt/tljh/user/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/tljh/user/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/tljh/user/lib/python3.12/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/jupyter-itproject2026/.local/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-6.1.0-py3-none-any.whl (740 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 740.6/740.6 kB 22.3 MB/s eta 0:00:00
Downloading faiss_cpu-1.15.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 28.8 MB/s eta 0:00:0000:0100:01
Downloading huggingface_hub-1.32.0-py3-none-any.whl (842 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 842.9/842.9 kB 28.5 MB/s eta 0:00:00
Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 29.4 MB/s eta 0:00:00
Downloading transformers-5.17.0-py3-none-any.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 30.1 MB/s eta 0:00:0000:010:01
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 22.4 MB/s eta 0:00:00
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Installing collected packages: safetensors, hf-xet, faiss-cpu, click, huggingface-hub, tokenizers, transformers, sentence-transformers
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.7.0
    Uninstalling safetensors-0.7.0:
      Successfully uninstalled safetensors-0.7.0
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.4.3
    Uninstalling hf-xet-1.4.3:
      Successfully uninstalled hf-xet-1.4.3
  Attempting uninstall: click
    Found existing installation: click 8.3.1
    Uninstalling click-8.3.1:
      Successfully uninstalled click-8.3.1
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
  WARNING: The scripts hf, huggingface-cli and tiny-agents are installed in '/home/jupyter-itproject2026/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.20.3
    Uninstalling tokenizers-0.20.3:
      Successfully uninstalled tokenizers-0.20.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.46.3
    Uninstalling transformers-4.46.3:
      Successfully uninstalled transformers-4.46.3
  WARNING: The script transformers is installed in '/home/jupyter-itproject2026/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed click-8.5.0 faiss-cpu-1.15.1 hf-xet-1.6.0 huggingface-hub-1.32.0 safetensors-0.8.0 sentence-transformers-6.1.0 tokenizers-0.23.2 transformers-5.17.0

In [76]:
from sentence_transformers import SentenceTransformer

In [77]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully.")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully.

In [78]:
print("Embedding dimension:", embedding_model.get_sentence_embedding_dimension())

Embedding dimension: 384

/tmp/ipykernel_514579/1529009797.py:1: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("Embedding dimension:", embedding_model.get_sentence_embedding_dimension())

In [79]:
mitre_texts = [
    document["text"]
    for document in mitre_documents
]

mitre_embeddings = embedding_model.encode(
    mitre_texts,
    show_progress_bar=True
)

print("Number of embeddings:", len(mitre_embeddings))
print("Embedding shape:", mitre_embeddings.shape)

Batches:   0%|          | 0/22 [00:00<?, ?it/s]

Number of embeddings: 697
Embedding shape: (697, 384)

In [80]:
import faiss
import numpy as np

# Convert embeddings to the format FAISS expects
mitre_embeddings = np.asarray(mitre_embeddings).astype("float32")

# Create a FAISS index using Euclidean distance
dimension = mitre_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

# Add all MITRE embeddings
index.add(mitre_embeddings)

print("FAISS index created successfully.")
print("Number of vectors:", index.ntotal)
print("Vector dimension:", dimension)

FAISS index created successfully.
Number of vectors: 697
Vector dimension: 384

In [8]:
def retrieve_mitre_evidence(query, top_k=5):
    query_embedding = embedding_model.encode(
        [query]
    ).astype("float32")

    distances, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for distance, idx in zip(distances[0], indices[0]):
        document = mitre_documents[idx]

        results.append({
            "technique_id": document["technique_id"],
            "name": document["name"],
            "distance": float(distance),
            "description": document["description"],
            "tactics": document["tactics"],
            "platforms": document["platforms"]
        })

    return results

In [82]:
results = retrieve_mitre_evidence(
    "process injection on a Windows system",
    top_k=5
)

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("Technique:", result["name"])
    print("ID:", result["technique_id"])
    print("Distance:", result["distance"])
    print("Tactics:", result["tactics"])
    print("Platforms:", result["platforms"])

Result 1
Technique: Process Injection
ID: T1055
Distance: 0.6692297458648682
Tactics: ['stealth', 'privilege-escalation']
Platforms: ['Linux', 'macOS', 'Windows']

Result 2
Technique: Portable Executable Injection
ID: T1055.002
Distance: 0.7207805514335632
Tactics: ['stealth', 'privilege-escalation']
Platforms: ['Windows']

Result 3
Technique: Process Hollowing
ID: T1055.012
Distance: 0.7637233734130859
Tactics: ['stealth', 'privilege-escalation']
Platforms: ['Windows']

Result 4
Technique: Dynamic-link Library Injection
ID: T1055.001
Distance: 0.8158191442489624
Tactics: ['stealth', 'privilege-escalation']
Platforms: ['Windows']

Result 5
Technique: Extra Window Memory Injection
ID: T1055.011
Distance: 0.8248459696769714
Tactics: ['stealth', 'privilege-escalation']
Platforms: ['Windows']

In [83]:
def create_rag_query(alert):
    query = f"""
    Network security alert.

    Destination port: {alert["service"]["destination_port"]}

    Flow duration: {alert["flow"]["duration"]}
    Forward packets: {alert["flow"]["forward_packets"]}
    Backward packets: {alert["flow"]["backward_packets"]}
    Forward bytes: {alert["flow"]["forward_bytes"]}
    Backward bytes: {alert["flow"]["backward_bytes"]}

    Bytes per second: {alert["traffic"]["bytes_per_second"]}
    Packets per second: {alert["traffic"]["packets_per_second"]}

    Forward packet rate: {alert["traffic"]["forward_packets_per_second"]}
    Backward packet rate: {alert["traffic"]["backward_packets_per_second"]}

    Forward packet length mean: {alert["packet_characteristics"]["forward_length_mean"]}
    Backward packet length mean: {alert["packet_characteristics"]["backward_length_mean"]}
    Packet length mean: {alert["packet_characteristics"]["packet_length_mean"]}
    Packet length standard deviation: {alert["packet_characteristics"]["packet_length_std"]}

    Flow IAT mean: {alert["timing"]["flow_iat_mean"]}
    Flow IAT standard deviation: {alert["timing"]["flow_iat_std"]}
    Flow IAT maximum: {alert["timing"]["flow_iat_max"]}
    Flow IAT minimum: {alert["timing"]["flow_iat_min"]}

    TCP SYN: {alert["tcp_flags"]["syn"]}
    TCP ACK: {alert["tcp_flags"]["ack"]}
    TCP FIN: {alert["tcp_flags"]["fin"]}
    TCP RST: {alert["tcp_flags"]["rst"]}
    TCP PSH: {alert["tcp_flags"]["psh"]}
    TCP URG: {alert["tcp_flags"]["urg"]}
    """

    return query.strip()

In [84]:
rag_query = create_rag_query(alerts[0])

print(rag_query)

Network security alert.

    Destination port: 3268.0

    Flow duration: 112740690.0
    Forward packets: 32.0
    Backward packets: 16.0
    Forward bytes: 6448.0
    Backward bytes: 1152.0

    Bytes per second: 67.41133126
    Packets per second: 0.425755776

    Forward packet rate: 0.283837184
    Backward packet rate: 0.141918592

    Forward packet length mean: 201.5
    Backward packet length mean: 72.0
    Packet length mean: 163.3265306
    Packet length standard deviation: 178.9317127

    Flow IAT mean: 2398738.085
    Flow IAT standard deviation: 5798697.94
    Flow IAT maximum: 16400000.0
    Flow IAT minimum: 3.0

    TCP SYN: 1.0
    TCP ACK: 1.0
    TCP FIN: 0.0
    TCP RST: 0.0
    TCP PSH: 0.0
    TCP URG: 0.0

In [85]:
results = retrieve_mitre_evidence(
    rag_query,
    top_k=5
)

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("Technique:", result["name"])
    print("ID:", result["technique_id"])
    print("Distance:", result["distance"])
    print("Tactics:", result["tactics"])
    print("Platforms:", result["platforms"])

Result 1
Technique: Web Protocols
ID: T1071.001
Distance: 1.195176124572754
Tactics: ['command-and-control']
Platforms: ['ESXi', 'Linux', 'macOS', 'Network Devices', 'Windows']

Result 2
Technique: Internet Connection Discovery
ID: T1016.001
Distance: 1.200697422027588
Tactics: ['discovery']
Platforms: ['Windows', 'Linux', 'macOS', 'ESXi']

Result 3
Technique: Internal Proxy
ID: T1090.001
Distance: 1.2023605108261108
Tactics: ['command-and-control']
Platforms: ['ESXi', 'Linux', 'macOS', 'Network Devices', 'Windows']

Result 4
Technique: DNS Calculation
ID: T1568.003
Distance: 1.2053587436676025
Tactics: ['command-and-control']
Platforms: ['ESXi', 'Linux', 'macOS', 'Windows']

Result 5
Technique: Traffic Signaling
ID: T1205
Distance: 1.2070327997207642
Tactics: ['stealth', 'persistence', 'command-and-control']
Platforms: ['Linux', 'macOS', 'Network Devices', 'Windows']

In [86]:
import os

nvd_path = "/home/jupyter-itproject2026/TrustSOC/data/knowledge_base/nvd_cve"

os.makedirs(nvd_path, exist_ok=True)

print("NVD directory created:")
print(nvd_path)

NVD directory created:
/home/jupyter-itproject2026/TrustSOC/data/knowledge_base/nvd_cve

In [87]:
import requests

nvd_url = "https://services.nvd.nist.gov/rest/json/cves/2.0"

response = requests.get(
    nvd_url,
    params={
        "resultsPerPage": 10
    },
    timeout=30
)

response.raise_for_status()

nvd_data = response.json()

print(nvd_data.keys())

dict_keys(['resultsPerPage', 'startIndex', 'totalResults', 'format', 'version', 'timestamp', 'vulnerabilities'])

In [88]:
print("Results per page:", nvd_data.get("resultsPerPage"))
print("Total results:", nvd_data.get("totalResults"))
print("Number retrieved:", len(nvd_data.get("vulnerabilities", [])))

Results per page: 10
Total results: 396909
Number retrieved: 10

In [89]:
cve_item = nvd_data["vulnerabilities"][0]["cve"]

print(cve_item.keys())

dict_keys(['id', 'sourceIdentifier', 'published', 'lastModified', 'vulnStatus', 'cveTags', 'descriptions', 'affected', 'metrics', 'weaknesses', 'configurations', 'references'])

In [90]:
print("CVE ID:", cve_item.get("id"))
print("Published:", cve_item.get("published"))
print("Last modified:", cve_item.get("lastModified"))
print("Status:", cve_item.get("vulnStatus"))

CVE ID: CVE-1999-0095
Published: 1988-10-01T04:00:00.000
Last modified: 2026-06-16T21:47:34.460
Status: Modified

In [91]:
print("Descriptions:")

for description in cve_item.get("descriptions", []):
    print("Language:", description.get("lang"))
    print("Text:", description.get("value"))
    print()

Descriptions:
Language: en
Text: The debug command in Sendmail is enabled, allowing attackers to execute commands as root.

Language: es
Text: El comando de depuración de Sendmail está activado, permitiendo a atacantes ejecutar comandos como root.

In [92]:
print("Metrics:", cve_item.get("metrics").keys())

Metrics: dict_keys(['cvssMetricV2'])

In [93]:
print("Weaknesses:")

for weakness in cve_item.get("weaknesses", []):
    print(weakness)

Weaknesses:
{'source': 'nvd@nist.gov', 'type': 'Primary', 'description': [{'lang': 'en', 'value': 'NVD-CWE-Other'}]}

In [94]:
print("Affected entries:", len(cve_item.get("affected", [])))

if cve_item.get("affected"):
    print(cve_item["affected"][0])

Affected entries: 1
{'source': 'cve@mitre.org', 'affectedData': [{'vendor': 'n/a', 'product': 'n/a', 'versions': [{'version': 'n/a', 'status': 'affected'}]}]}

In [95]:
def extract_cve_document(cve_item):
    # English description
    description = ""

    for item in cve_item.get("descriptions", []):
        if item.get("lang") == "en":
            description = item.get("value", "")
            break

    # CWE
    weaknesses = []

    for weakness in cve_item.get("weaknesses", []):
        for item in weakness.get("description", []):
            if item.get("lang") == "en":
                weaknesses.append(item.get("value", ""))

    # Affected products
    affected_products = []

    for affected in cve_item.get("affected", []):
        vendor = affected.get("vendor", "unknown")
        product = affected.get("product", "unknown")

        affected_products.append({
            "vendor": vendor,
            "product": product
        })

    # CVSS information
    cvss = {}

    metrics = cve_item.get("metrics", {})

    for metric_type, metric_list in metrics.items():

        if not metric_list:
            continue

        metric = metric_list[0]

        cvss_data = metric.get("cvssData", {})

        cvss[metric_type] = {
            "version": cvss_data.get("version"),
            "base_score": cvss_data.get("baseScore"),
            "vector": cvss_data.get("vectorString")
        }

    document = {
        "source": "NVD",
        "type": "cve",
        "cve_id": cve_item.get("id"),
        "description": description,
        "published": cve_item.get("published"),
        "last_modified": cve_item.get("lastModified"),
        "status": cve_item.get("vulnStatus"),
        "weaknesses": weaknesses,
        "affected_products": affected_products,
        "cvss": cvss
    }

    return document

In [96]:
cve_document = extract_cve_document(cve_item)

print(cve_document)

{'source': 'NVD', 'type': 'cve', 'cve_id': 'CVE-1999-0095', 'description': 'The debug command in Sendmail is enabled, allowing attackers to execute commands as root.', 'published': '1988-10-01T04:00:00.000', 'last_modified': '2026-06-16T21:47:34.460', 'status': 'Modified', 'weaknesses': ['NVD-CWE-Other'], 'affected_products': [{'vendor': 'unknown', 'product': 'unknown'}], 'cvss': {'cvssMetricV2': {'version': '2.0', 'base_score': 10.0, 'vector': 'AV:N/AC:L/Au:N/C:C/I:C/A:C'}}}

In [97]:
def create_cve_text(document):
    weaknesses = ", ".join(document["weaknesses"])

    products = []

    for product in document["affected_products"]:
        products.append(
            f'{product["vendor"]} {product["product"]}'
        )

    products_text = ", ".join(products)

    cvss_parts = []

    for metric_type, metric in document["cvss"].items():
        cvss_parts.append(
            f'{metric_type}: '
            f'CVSS {metric["version"]}, '
            f'base score {metric["base_score"]}, '
            f'vector {metric["vector"]}'
        )

    cvss_text = "; ".join(cvss_parts)

    text = f"""
Source: {document["source"]}
Type: {document["type"]}
CVE ID: {document["cve_id"]}

Description:
{document["description"]}

Published:
{document["published"]}

Last Modified:
{document["last_modified"]}

Status:
{document["status"]}

Weaknesses:
{weaknesses}

Affected Products:
{products_text}

CVSS:
{cvss_text}
""".strip()

    return text

In [98]:
cve_document["text"] = create_cve_text(cve_document)

print(cve_document["text"])

Source: NVD
Type: cve
CVE ID: CVE-1999-0095

Description:
The debug command in Sendmail is enabled, allowing attackers to execute commands as root.

Published:
1988-10-01T04:00:00.000

Last Modified:
2026-06-16T21:47:34.460

Status:
Modified

Weaknesses:
NVD-CWE-Other

Affected Products:
unknown unknown

CVSS:
cvssMetricV2: CVSS 2.0, base score 10.0, vector AV:N/AC:L/Au:N/C:C/I:C/A:C

In [99]:
response = requests.get(
    nvd_url,
    params={
        "resultsPerPage": 100,
        "startIndex": 0
    },
    timeout=60
)

response.raise_for_status()

nvd_sample = response.json()

print("Retrieved:", len(nvd_sample["vulnerabilities"]))
print("Total available:", nvd_sample["totalResults"])

Retrieved: 100
Total available: 396909

In [100]:
nvd_documents = []

for item in nvd_sample["vulnerabilities"]:
    cve = item["cve"]

    document = extract_cve_document(cve)
    document["text"] = create_cve_text(document)

    nvd_documents.append(document)

print("NVD documents created:", len(nvd_documents))

NVD documents created: 100

In [101]:
for document in nvd_documents[:3]:
    print("=" * 70)
    print(document["cve_id"])
    print(document["text"][:1000])

======================================================================
CVE-1999-0095
Source: NVD
Type: cve
CVE ID: CVE-1999-0095

Description:
The debug command in Sendmail is enabled, allowing attackers to execute commands as root.

Published:
1988-10-01T04:00:00.000

Last Modified:
2026-06-16T21:47:34.460

Status:
Modified

Weaknesses:
NVD-CWE-Other

Affected Products:
unknown unknown

CVSS:
cvssMetricV2: CVSS 2.0, base score 10.0, vector AV:N/AC:L/Au:N/C:C/I:C/A:C
======================================================================
CVE-1999-0082
Source: NVD
Type: cve
CVE ID: CVE-1999-0082

Description:
CWD ~root command in ftpd allows root access.

Published:
1988-11-11T05:00:00.000

Last Modified:
2026-06-16T21:47:32.300

Status:
Modified

Weaknesses:
NVD-CWE-Other

Affected Products:
unknown unknown

CVSS:
cvssMetricV2: CVSS 2.0, base score 10.0, vector AV:N/AC:L/Au:N/C:C/I:C/A:C
======================================================================
CVE-1999-1471
Source: NVD
Type: cve
CVE ID: CVE-1999-1471

Description:
Buffer overflow in passwd in BSD based operating systems 4.3 and earlier allows local users to gain root privileges by specifying a long shell or GECOS field.

Published:
1989-01-01T05:00:00.000

Last Modified:
2026-06-16T21:50:30.747

Status:
Modified

Weaknesses:
NVD-CWE-Other

Affected Products:
unknown unknown

CVSS:
cvssMetricV2: CVSS 2.0, base score 7.2, vector AV:L/AC:L/Au:N/C:C/I:C/A:C

In [102]:
nvd_processed_file = os.path.join(
    nvd_path,
    "nvd_cve_documents_pilot.json"
)

with open(nvd_processed_file, "w", encoding="utf-8") as f:
    json.dump(
        nvd_documents,
        f,
        indent=2,
        ensure_ascii=False
    )

print("NVD pilot corpus saved.")
print("Path:", nvd_processed_file)
print(
    "Size:",
    round(os.path.getsize(nvd_processed_file) / (1024 * 1024), 2),
    "MB"
)

NVD pilot corpus saved.
Path: /home/jupyter-itproject2026/TrustSOC/data/knowledge_base/nvd_cve/nvd_cve_documents_pilot.json
Size: 0.11 MB

In [103]:
print(os.listdir(nvd_path))

['nvd_cve_documents_pilot.json']

In [104]:
nvd_texts = [
    document["text"]
    for document in nvd_documents
]

nvd_embeddings = embedding_model.encode(
    nvd_texts,
    show_progress_bar=True
)

nvd_embeddings = np.asarray(nvd_embeddings).astype("float32")

print("NVD embeddings:", nvd_embeddings.shape)

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

NVD embeddings: (100, 384)

In [105]:
nvd_index = faiss.IndexFlatL2(
    nvd_embeddings.shape[1]
)

nvd_index.add(nvd_embeddings)

print("NVD FAISS index created.")
print("Number of vectors:", nvd_index.ntotal)
print("Vector dimension:", nvd_embeddings.shape[1])

NVD FAISS index created.
Number of vectors: 100
Vector dimension: 384

In [106]:
def retrieve_nvd_evidence(query, top_k=5):
    query_embedding = embedding_model.encode(
        [query]
    ).astype("float32")

    distances, indices = nvd_index.search(
        query_embedding,
        top_k
    )

    results = []

    for distance, idx in zip(distances[0], indices[0]):
        document = nvd_documents[idx]

        results.append({
            "source": "NVD",
            "cve_id": document["cve_id"],
            "distance": float(distance),
            "description": document["description"],
            "weaknesses": document["weaknesses"],
            "affected_products": document["affected_products"],
            "cvss": document["cvss"]
        })

    return results

In [107]:
results = retrieve_nvd_evidence(
    "remote command execution vulnerability",
    top_k=5
)

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("CVE:", result["cve_id"])
    print("Distance:", result["distance"])
    print("Description:", result["description"])

Result 1
CVE: CVE-1999-0207
Distance: 0.9473655223846436
Description: Remote attacker can execute commands through Majordomo using the Reply-To field and a "lists" command.

Result 2
CVE: CVE-1999-1467
Distance: 1.0974607467651367
Description: Vulnerability in rcp on SunOS 4.0.x allows remote attackers from trusted hosts to execute arbitrary commands as root, possibly related to the configuration of the nobody user.

Result 3
CVE: CVE-1999-0155
Distance: 1.143064022064209
Description: The ghostscript command with the -dSAFER option allows remote attackers to execute commands.

Result 4
CVE: CVE-1999-1059
Distance: 1.164713978767395
Description: Vulnerability in rexec daemon (rexecd) in AT&T TCP/IP 4.0 for various SVR4 systems allows remote attackers to execute arbitrary commands.

Result 5
CVE: CVE-1999-1119
Distance: 1.210087776184082
Description: FTP installation script anon.ftp in AIX insecurely configures anonymous FTP, which allows remote attackers to execute arbitrary commands.

In [110]:
def retrieve_evidence(query, top_k=5):
    mitre_results = retrieve_mitre_evidence(
        query,
        top_k=top_k
    )

    nvd_results = retrieve_nvd_evidence(
        query,
        top_k=top_k
    )

    evidence = []

    for result in mitre_results:
        evidence.append({
            "source": "MITRE ATT&CK",
            "id": result["technique_id"],
            "name": result["name"],
            "distance": result["distance"],
            "evidence": result["description"],
            "tactics": result["tactics"],
            "platforms": result["platforms"]
        })

    for result in nvd_results:
        evidence.append({
            "source": "NVD",
            "id": result["cve_id"],
            "name": result["cve_id"],
            "distance": result["distance"],
            "evidence": result["description"],
            "weaknesses": result["weaknesses"],
            "affected_products": result["affected_products"],
            "cvss": result["cvss"]
        })

    return evidence

In [111]:
evidence = retrieve_evidence(
    "remote command execution vulnerability",
    top_k=3
)

for i, item in enumerate(evidence, 1):
    print(f"\nEvidence {i}")
    print("Source:", item["source"])
    print("ID:", item["id"])
    print("Name:", item["name"])
    print("Distance:", item["distance"])
    print("Evidence:", item["evidence"][:300])

Evidence 1
Source: MITRE ATT&CK
ID: T1059.003
Name: Windows Command Shell
Distance: 0.8512182235717773
Evidence: Adversaries may abuse the Windows command shell for execution. The Windows command shell ([cmd](https://attack.mitre.org/software/S0106)) is the primary command prompt on Windows systems. The Windows command prompt can be used to control almost any aspect of a system, with various permission levels

Evidence 2
Source: MITRE ATT&CK
ID: T1059.001
Name: PowerShell
Distance: 0.9779573678970337
Evidence: Adversaries may abuse PowerShell commands and scripts for execution. PowerShell is a powerful interactive command-line interface and scripting environment included in the Windows operating system.(Citation: TechNet PowerShell) Adversaries can use PowerShell to perform a number of actions, including

Evidence 3
Source: MITRE ATT&CK
ID: T1059
Name: Command and Scripting Interpreter
Distance: 0.986407995223999
Evidence: Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries. These interfaces and languages provide ways of interacting with computer systems and are a common feature across many different platforms. Most systems come with some built-in command-line interface and

Evidence 4
Source: NVD
ID: CVE-1999-0207
Name: CVE-1999-0207
Distance: 0.9473655223846436
Evidence: Remote attacker can execute commands through Majordomo using the Reply-To field and a "lists" command.

Evidence 5
Source: NVD
ID: CVE-1999-1467
Name: CVE-1999-1467
Distance: 1.0974607467651367
Evidence: Vulnerability in rcp on SunOS 4.0.x allows remote attackers from trusted hosts to execute arbitrary commands as root, possibly related to the configuration of the nobody user.

Evidence 6
Source: NVD
ID: CVE-1999-0155
Name: CVE-1999-0155
Distance: 1.143064022064209
Evidence: The ghostscript command with the -dSAFER option allows remote attackers to execute commands.

In [112]:
# Prepare the input for the Threat Intelligence Agent

def prepare_threat_intelligence_input(alert, evidence):
    agent_input = {
        "alert": alert,
        "retrieved_evidence": evidence
    }

    return agent_input

In [113]:
threat_input = prepare_threat_intelligence_input(
    sample_alert,
    evidence
)

print(threat_input.keys())

dict_keys(['alert', 'retrieved_evidence'])

In [114]:
def threat_intelligence_agent(agent_input):
    alert = agent_input["alert"]
    evidence = agent_input["retrieved_evidence"]

    assessment = {
        "agent": "Threat Intelligence Agent",
        "alert_id": alert["alert_id"],
        "assessment": "",
        "relevant_evidence": [],
        "confidence": 0.0,
        "reasoning": "",
        "limitations": []
    }

    if len(evidence) == 0:
        assessment["assessment"] = "Insufficient threat intelligence evidence."
        assessment["confidence"] = 0.0
        assessment["reasoning"] = (
            "No external cybersecurity evidence was retrieved for this alert."
        )
        assessment["limitations"].append(
            "The available alert features alone are insufficient to establish "
            "a specific threat technique or vulnerability."
        )

        return assessment

    assessment["relevant_evidence"] = evidence

    assessment["assessment"] = (
        "Cybersecurity evidence was retrieved, but its direct applicability "
        "to the alert requires further analysis."
    )

    assessment["confidence"] = 0.5

    assessment["reasoning"] = (
        "The agent reviewed the retrieved MITRE ATT&CK and NVD evidence. "
        "The retrieved information is semantically related to the query, "
        "but the available network-flow features do not directly establish "
        "that a specific ATT&CK technique or CVE applies to this alert."
    )

    assessment["limitations"].append(
        "CICIDS2017 flow features do not directly provide process, host, "
        "software, or vulnerability information."
    )

    return assessment

In [115]:
threat_assessment = threat_intelligence_agent(threat_input)

print(threat_assessment)

{'agent': 'Threat Intelligence Agent', 'alert_id': 'ALERT_0001', 'assessment': 'Cybersecurity evidence was retrieved, but its direct applicability to the alert requires further analysis.', 'relevant_evidence': [{'source': 'MITRE ATT&CK', 'id': 'T1059.003', 'name': 'Windows Command Shell', 'distance': 0.8512182235717773, 'evidence': 'Adversaries may abuse the Windows command shell for execution. The Windows command shell ([cmd](https://attack.mitre.org/software/S0106)) is the primary command prompt on Windows systems. The Windows command prompt can be used to control almost any aspect of a system, with various permission levels required for different subsets of commands. The command prompt can be invoked remotely via [Remote Services](https://attack.mitre.org/techniques/T1021) such as [SSH](https://attack.mitre.org/techniques/T1021/004).(Citation: SSH in Windows)\n\nBatch files (ex: .bat or .cmd) also provide the shell with a list of sequential commands to run, as well as normal scripting operations such as conditionals and loops. Common uses of batch files include long or repetitive tasks, or the need to run the same set of commands on multiple systems.\n\nAdversaries may leverage [cmd](https://attack.mitre.org/software/S0106) to execute various commands and payloads. Common uses include [cmd](https://attack.mitre.org/software/S0106) to execute a single command, or abusing [cmd](https://attack.mitre.org/software/S0106) interactively with input and output forwarded over a command and control channel.', 'tactics': ['execution'], 'platforms': ['Windows']}, {'source': 'MITRE ATT&CK', 'id': 'T1059.001', 'name': 'PowerShell', 'distance': 0.9779573678970337, 'evidence': "Adversaries may abuse PowerShell commands and scripts for execution. PowerShell is a powerful interactive command-line interface and scripting environment included in the Windows operating system.(Citation: TechNet PowerShell) Adversaries can use PowerShell to perform a number of actions, including discovery of information and execution of code. Examples include the <code>Start-Process</code> cmdlet which can be used to run an executable and the <code>Invoke-Command</code> cmdlet which runs a command locally or on a remote computer (though administrator permissions are required to use PowerShell to connect to remote systems).\n\nPowerShell may also be used to download and run executables from the Internet, which can be executed from disk or in memory without touching disk.\n\nA number of PowerShell-based offensive testing tools are available, including [Empire](https://attack.mitre.org/software/S0363),  [PowerSploit](https://attack.mitre.org/software/S0194), [PoshC2](https://attack.mitre.org/software/S0378), and PSAttack.(Citation: Github PSAttack)\n\nPowerShell commands/scripts can also be executed without directly invoking the <code>powershell.exe</code> binary through interfaces to PowerShell's underlying <code>System.Management.Automation</code> assembly DLL exposed through the .NET framework and Windows Common Language Interface (CLI).(Citation: Sixdub PowerPick Jan 2016)(Citation: SilentBreak Offensive PS Dec 2015)(Citation: Microsoft PSfromCsharp APR 2014)", 'tactics': ['execution'], 'platforms': ['Windows']}, {'source': 'MITRE ATT&CK', 'id': 'T1059', 'name': 'Command and Scripting Interpreter', 'distance': 0.986407995223999, 'evidence': 'Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries. These interfaces and languages provide ways of interacting with computer systems and are a common feature across many different platforms. Most systems come with some built-in command-line interface and scripting capabilities, for example, macOS and Linux distributions include some flavor of [Unix Shell](https://attack.mitre.org/techniques/T1059/004) while Windows installations include the [Windows Command Shell](https://attack.mitre.org/techniques/T1059/003) and [PowerShell](https://attack.mitre.org/techniques/T1059/001).\n\nThere are also cross-platform interpreters such as [Python](https://attack.mitre.org/techniques/T1059/006), as well as those commonly associated with client applications such as [JavaScript](https://attack.mitre.org/techniques/T1059/007) and [Visual Basic](https://attack.mitre.org/techniques/T1059/005).\n\nAdversaries may abuse these technologies in various ways as a means of executing arbitrary commands. Commands and scripts can be embedded in [Initial Access](https://attack.mitre.org/tactics/TA0001) payloads delivered to victims as lure documents or as secondary payloads downloaded from an existing C2. Adversaries may also execute commands through interactive terminals/shells, as well as utilize various [Remote Services](https://attack.mitre.org/techniques/T1021) in order to achieve remote Execution.(Citation: Powershell Remote Commands)(Citation: Cisco IOS Software Integrity Assurance - Command History)(Citation: Remote Shell Execution in Python)', 'tactics': ['execution'], 'platforms': ['Containers', 'ESXi', 'IaaS', 'Identity Provider', 'Linux', 'macOS', 'Network Devices', 'Office Suite', 'SaaS', 'Windows']}, {'source': 'NVD', 'id': 'CVE-1999-0207', 'name': 'CVE-1999-0207', 'distance': 0.9473655223846436, 'evidence': 'Remote attacker can execute commands through Majordomo using the Reply-To field and a "lists" command.', 'weaknesses': ['NVD-CWE-Other'], 'affected_products': [{'vendor': 'unknown', 'product': 'unknown'}], 'cvss': {'cvssMetricV2': {'version': '2.0', 'base_score': 7.5, 'vector': 'AV:N/AC:L/Au:N/C:P/I:P/A:P'}}}, {'source': 'NVD', 'id': 'CVE-1999-1467', 'name': 'CVE-1999-1467', 'distance': 1.0974607467651367, 'evidence': 'Vulnerability in rcp on SunOS 4.0.x allows remote attackers from trusted hosts to execute arbitrary commands as root, possibly related to the configuration of the nobody user.', 'weaknesses': ['NVD-CWE-Other'], 'affected_products': [{'vendor': 'unknown', 'product': 'unknown'}], 'cvss': {'cvssMetricV2': {'version': '2.0', 'base_score': 10.0, 'vector': 'AV:N/AC:L/Au:N/C:C/I:C/A:C'}}}, {'source': 'NVD', 'id': 'CVE-1999-0155', 'name': 'CVE-1999-0155', 'distance': 1.143064022064209, 'evidence': 'The ghostscript command with the -dSAFER option allows remote attackers to execute commands.', 'weaknesses': ['NVD-CWE-Other'], 'affected_products': [{'vendor': 'unknown', 'product': 'unknown'}], 'cvss': {'cvssMetricV2': {'version': '2.0', 'base_score': 7.5, 'vector': 'AV:N/AC:L/Au:N/C:P/I:P/A:P'}}}], 'confidence': 0.5, 'reasoning': 'The agent reviewed the retrieved MITRE ATT&CK and NVD evidence. The retrieved information is semantically related to the query, but the available network-flow features do not directly establish that a specific ATT&CK technique or CVE applies to this alert.', 'limitations': ['CICIDS2017 flow features do not directly provide process, host, software, or vulnerability information.']}

In [116]:
import os

print("OPENAI_API_KEY available:", bool(os.getenv("OPENAI_API_KEY")))
print("GROQ_API_KEY available:", bool(os.getenv("GROQ_API_KEY")))
print("GOOGLE_API_KEY available:", bool(os.getenv("GOOGLE_API_KEY")))

OPENAI_API_KEY available: False
GROQ_API_KEY available: False
GOOGLE_API_KEY available: False

In [117]:
import importlib.util

packages = [
    "openai",
    "google.generativeai",
    "groq",
    "transformers",
    "torch",
    "langchain",
    "langgraph"
]

for package in packages:
    module_name = package.split(".")[0]
    installed = importlib.util.find_spec(module_name) is not None
    print(f"{package}: {installed}")

openai: False
google.generativeai: True
groq: False
transformers: True
torch: True
langchain: False
langgraph: False

In [118]:
import os

google_keys = [
    key for key in os.environ
    if "GOOGLE" in key.upper() or "GEMINI" in key.upper()
]

print("Google/Gemini environment variables found:")
print(google_keys)

Google/Gemini environment variables found:
[]

In [120]:
import torch
import transformers

print("Transformers version:", transformers.__version__)
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

Transformers version: 5.17.0
PyTorch version: 2.5.1+cu121
CUDA available: True

In [121]:
from transformers import pipeline

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

generator = pipeline(
    "text-generation",
    model=model_name,
    device=0
)

print("Threat Intelligence LLM loaded successfully.")

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Threat Intelligence LLM loaded successfully.

In [122]:
test_prompt = """
You are a cybersecurity threat intelligence analyst.

Analyze this simple observation:

A network connection was established to destination port 3268.
The flow contains 32 forward packets and 16 backward packets.
A TCP SYN and ACK were observed.

Do not assume that the connection is malicious.
State only what can reasonably be concluded from these observations.
"""

response = generator(
    test_prompt,
    max_new_tokens=150,
    do_sample=False
)

print(response[0]["generated_text"])

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

You are a cybersecurity threat intelligence analyst.

Analyze this simple observation:

A network connection was established to destination port 3268.
The flow contains 32 forward packets and 16 backward packets.
A TCP SYN and ACK were observed.

Do not assume that the connection is malicious.
State only what can reasonably be concluded from these observations.
Based on the given information, it seems like the connection has been established but there may have been some issues with the initial handshake or the subsequent data transfer. The presence of 32 forward packets suggests that the connection might have been initiated successfully, while the 16 backward packets indicate that the connection may have encountered some kind of error during the data transfer process. This could potentially lead to issues such as packet loss, incorrect data transmission, or other problems that could compromise the security of the network. It's important to monitor the connection closely for any signs of further issues or unusual behavior. Additionally, if the connection is suspected to be compromised, it would be advisable to take appropriate action to secure the network and prevent further unauthorized access.

Please note

In [129]:
def build_threat_intelligence_prompt(agent_input):

    alert = agent_input["alert"]
    evidence = agent_input["retrieved_evidence"]

    prompt = f"""
You are the Threat Intelligence Agent in a SOC decision-support system.

Analyze the alert using ONLY the alert information and retrieved evidence.

STRICT RULES:
1. Never invent facts.
2. Never assume retrieved evidence applies to the alert.
3. Retrieval similarity does not prove applicability.
4. Network-flow statistics do not prove execution of commands,
   scripts, malware, vulnerabilities, or MITRE ATT&CK techniques.
5. A destination port does not identify a specific application or vulnerability.
6. Do not infer attacker identity, motivation, intent, or target.
7. Do not call the alert malicious unless the supplied evidence supports it.
8. Do not use retrieval distance as confidence or probability.
9. If no technique or vulnerability can be established, say so explicitly.
10. Do not provide recommendations.

ALERT:
Alert ID: {alert["alert_id"]}

Service:
{alert["service"]}

Flow:
{alert["flow"]}

Traffic:
{alert["traffic"]}

Packet Characteristics:
{alert["packet_characteristics"]}

Timing:
{alert["timing"]}

TCP Flags:
{alert["tcp_flags"]}

Connection:
{alert["connection"]}

RETRIEVED EVIDENCE:
"""

    for i, item in enumerate(evidence, start=1):
        prompt += f"""
Evidence {i}
Source: {item["source"]}
ID: {item["id"]}
Name: {item["name"]}
Retrieval Distance: {item["distance"]}
Description: {item["evidence"]}
"""

    prompt += """
TASK:

Determine whether any retrieved evidence is actually supported
by the alert.

You MUST use the exact output format below.

Observed Facts:
- <directly observed fact>
- <directly observed fact>

Evidence Applicability:
- Evidence 1: <Supported / Not Supported / Insufficient Information>
- Evidence 2: <Supported / Not Supported / Insufficient Information>
- Evidence 3: <Supported / Not Supported / Insufficient Information>
- Evidence 4: <Supported / Not Supported / Insufficient Information>
- Evidence 5: <Supported / Not Supported / Insufficient Information>
- Evidence 6: <Supported / Not Supported / Insufficient Information>

Threat Assessment:
<maximum two sentences>

Specific Technique or Vulnerability:
<specific technique/CVE only if established>
OR
No specific threat technique or vulnerability is established.

Confidence:
<Low / Medium / High>

Limitations:
- <missing information that limits the assessment>

IMPORTANT:
Do not output anything after the Limitations section.
Do not output a Recommendation section.
Do not repeat these instructions.
"""

    return prompt

In [131]:
threat_prompt = build_threat_intelligence_prompt(threat_input)

In [132]:
response = generator(
    threat_prompt,
    max_new_tokens=200,
    do_sample=False,
    return_full_text=False
)

agent_output = response[0]["generated_text"]

print(agent_output)

[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Do not output any other sections.

Observation Facts:
The alert contains a TCP flow with a source IP address of 192.168.1.100 and a destination IP address of 192.168.1.101.

Evidence Applicability:
Evidence 1: Supported
Evidence 2: Supported
Evidence 3: Supported
Evidence 4: Supported
Evidence 5: Supported
Evidence 6: Supported

Threat Assessment:
The evidence provided supports the detection of a potential attack vector by identifying the source and destination IP addresses of the alert. This suggests that there may be an attempt to exploit a network security vulnerability or command injection technique.

Specific Technique or Vulnerability:
The evidence indicates that the source IP address (192.168.1.100) is likely connected to a compromised system, suggesting that the attack could potentially originate from within the organization's network. The destination IP address

In [1]:

from pathlib import Path
import pandas as pd

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)

csv_files = sorted(data_dir.glob("*.csv"))

print("Number of CSV files found:", len(csv_files))
print()

dataset_summary = []

for file_path in csv_files:
    print("Inspecting:", file_path.name)

    try:
        data = pd.read_csv(file_path, low_memory=False)
        data.columns = data.columns.str.strip()

        if "Label" not in data.columns:
            print("  WARNING: Label column missing")
            continue

        labels = data["Label"].astype("string").str.strip()
        counts = labels.value_counts(dropna=False)

        print("  Rows:", len(data))
        print("  Columns:", len(data.columns))
        print("  Unique labels:", labels.nunique(dropna=True))
        print("  Top labels:")
        print(counts.head(10).to_string())
        print()

        for label, count in counts.items():
            dataset_summary.append({
                "file": file_path.name,
                "rows": len(data),
                "label": str(label),
                "count": int(count),
                "percentage": round(
                    count / len(data) * 100, 4
                ) if len(data) else 0
            })

    except Exception as error:
        print("  ERROR:", repr(error))
        print("  This file needs separate inspection.")
        print()

label_summary = pd.DataFrame(dataset_summary)

print("\nOVERALL SUMMARY BY FILE AND LABEL")
display(label_summary)

Number of CSV files found: 8

Inspecting: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
  WARNING: Label column missing
Inspecting: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
  WARNING: Label column missing
Inspecting: Friday-WorkingHours-Morning.pcap_ISCX.csv
  Rows: 191033
  Columns: 79
  Unique labels: 2
  Top labels:
Label
BENIGN    189067
Bot         1966

Inspecting: Monday-WorkingHours.pcap_ISCX.csv
  WARNING: Label column missing
Inspecting: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
  WARNING: Label column missing
Inspecting: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
  Rows: 170366
  Columns: 79
  Unique labels: 4
  Top labels:
Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21

Inspecting: Tuesday-WorkingHours.pcap_ISCX.csv
  Rows: 209817
  Columns: 79
  Unique labels: 3
  Top labels:
Label
BENIGN         198905
FTP-Patator      7938
SSH-Patator      2973
<NA>                1

Inspecting: Wednesday-workingHours.pcap_ISCX.csv
  Rows: 185944
  Columns: 79
  Unique labels: 4
  Top labels:
Label
DoS Hulk            105457
BENIGN               69191
DoS slowloris         5796
DoS Slowhttptest      5499
<NA>                     1


OVERALL SUMMARY BY FILE AND LABEL

,file,rows,label,count,percentage
0,Friday-WorkingHours-Morning.pcap_ISCX.csv,191033,BENIGN,189067,98.9709
1,Friday-WorkingHours-Morning.pcap_ISCX.csv,191033,Bot,1966,1.0291
2,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,BENIGN,168186,98.7204
3,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,Web Attack � Brute Force,1507,0.8846
4,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,Web Attack � XSS,652,0.3827
5,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,Web Attack � Sql Injection,21,0.0123
6,Tuesday-WorkingHours.pcap_ISCX.csv,209817,BENIGN,198905,94.7993
7,Tuesday-WorkingHours.pcap_ISCX.csv,209817,FTP-Patator,7938,3.7833
8,Tuesday-WorkingHours.pcap_ISCX.csv,209817,SSH-Patator,2973,1.4169
9,Tuesday-WorkingHours.pcap_ISCX.csv,209817,<NA>,1,0.0005
10,Wednesday-workingHours.pcap_ISCX.csv,185944,DoS Hulk,105457,56.7144
11,Wednesday-workingHours.pcap_ISCX.csv,185944,BENIGN,69191,37.2107
12,Wednesday-workingHours.pcap_ISCX.csv,185944,DoS slowloris,5796,3.1171
13,Wednesday-workingHours.pcap_ISCX.csv,185944,DoS Slowhttptest,5499,2.9573
14,Wednesday-workingHours.pcap_ISCX.csv,185944,<NA>,1,0.0005

In [2]:

import csv
import pandas as pd
from pathlib import Path

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)

files_to_check = [
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv"
]

for filename in files_to_check:
    path = data_dir / filename

    print("\n" + "=" * 80)
    print("FILE:", filename)

    # Inspect the original header without modifying it
    with open(path, "r", encoding="utf-8-sig",
              errors="replace", newline="") as file:
        reader = csv.reader(file)
        for row_number, row in zip(range(3), reader):
            print(f"\nRaw CSV row {row_number}:")
            print("Number of fields:", len(row))
            print("First 5 fields:", repr(row[:5]))
            print("Last 5 fields:", repr(row[-5:]))

    # Inspect pandas' interpretation of the header
    try:
        df_check = pd.read_csv(path, nrows=3, low_memory=False)

        print("\nPandas column count:", len(df_check.columns))
        print("First 5 column names:",
              [repr(col) for col in df_check.columns[:5]])
        print("Last 10 column names:",
              [repr(col) for col in df_check.columns[-10:]])

        label_like = [
            col for col in df_check.columns
            if "label" in str(col).lower()
            or "class" in str(col).lower()
        ]
        print("Label/class-like columns:", label_like)

    except Exception as error:
        print("Pandas read error:", repr(error))

================================================================================
FILE: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv

Raw CSV row 0:
Number of fields: 20
First 5 fields: ['', '0', '0', '2', '70']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 1:
Number of fields: 79
First 5 fields: ['53', '23802', '2', '2', '72']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 2:
Number of fields: 79
First 5 fields: ['53', '55782', '4', '4', '136']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Pandas column count: 20
First 5 column names: ["'Unnamed: 0'", "'0'", "'0.1'", "'2'", "'70'"]
Last 10 column names: ["'20'", "'0.2'", "'0.3'", "'0.4'", "'0.5'", "'0.6'", "'0.7'", "'0.8'", "'0.9'", "'BENIGN'"]
Label/class-like columns: []

================================================================================
FILE: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv

Raw CSV row 0:
Number of fields: 62
First 5 fields: ['71', '327', '3', '330', '165']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 1:
Number of fields: 79
First 5 fields: ['443', '32027', '3', '4', '92']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 2:
Number of fields: 79
First 5 fields: ['53270', '198', '2', '1', '0']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Pandas column count: 62
First 5 column names: ["'71'", "'327'", "'3'", "'330'", "'165'"]
Last 10 column names: ["'20'", "'0.30'", "'0.31'", "'0.32'", "'0.33'", "'0.34'", "'0.35'", "'0.36'", "'0.37'", "'BENIGN'"]
Label/class-like columns: []

================================================================================
FILE: Monday-WorkingHours.pcap_ISCX.csv

Raw CSV row 0:
Number of fields: 63
First 5 fields: ['0980', '0', '170980', '170980', '0']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 1:
Number of fields: 79
First 5 fields: ['53', '48748', '2', '2', '92']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 2:
Number of fields: 79
First 5 fields: ['53', '40793', '1', '1', '44']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Pandas column count: 63
First 5 column names: ["'0980'", "'0'", "'170980'", "'170980.1'", "'0.1'"]
Last 10 column names: ["'32.3'", "'0.30'", "'0.31'", "'0.32'", "'0.33'", "'0.34'", "'0.35'", "'0.36'", "'0.37'", "'BENIGN'"]
Label/class-like columns: []

================================================================================
FILE: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv

Raw CSV row 0:
Number of fields: 63
First 5 fields: ['33333', '27997.4466', '48496', '3', '3']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 1:
Number of fields: 79
First 5 fields: ['21', '2784123', '6', '7', '31']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Raw CSV row 2:
Number of fields: 79
First 5 fields: ['43510', '61', '1', '1', '0']
Last 5 fields: ['0', '0', '0', '0', 'BENIGN']

Pandas column count: 63
First 5 column names: ["'33333'", "'27997.4466'", "'48496'", "'3'", "'3.1'"]
Last 10 column names: ["'40'", "'0.20'", "'0.21'", "'0.22'", "'0.23'", "'0.24'", "'0.25'", "'0.26'", "'0.27'", "'BENIGN'"]
Label/class-like columns: []

In [3]:

import csv
from pathlib import Path

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)

files_to_check = [
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv"
]

expected_headers = {
    "Destination Port",
    "Flow Duration",
    "Total Fwd Packets",
    "Total Backward Packets",
    "Flow Bytes/s",
    "Label"
}

for filename in files_to_check:
    path = data_dir / filename

    print("\n" + "=" * 80)
    print("FILE:", filename)

    with open(
        path, "r", encoding="utf-8-sig",
        errors="replace", newline=""
    ) as file:
        reader = csv.reader(file)

        found_header = False

        for line_number, row in enumerate(reader, start=1):
            if line_number > 30:
                break

            normalized = {value.strip() for value in row}
            matches = expected_headers.intersection(normalized)

            if len(matches) >= 4:
                print("Possible header found at line:", line_number)
                print("Number of fields:", len(row))
                print("Matched expected names:", sorted(matches))
                print("Last 8 fields:", row[-8:])
                found_header = True
                break

        if not found_header:
            print("No matching header found in the first 30 lines.")

================================================================================
FILE: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
No matching header found in the first 30 lines.

================================================================================
FILE: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
No matching header found in the first 30 lines.

================================================================================
FILE: Monday-WorkingHours.pcap_ISCX.csv
No matching header found in the first 30 lines.

================================================================================
FILE: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
No matching header found in the first 30 lines.

In [4]:

import csv
from collections import Counter
from pathlib import Path

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)

reference_path = (
    data_dir / "Friday-WorkingHours-Morning.pcap_ISCX.csv"
)

# Get the known-good header from the clean reference file.
with open(
    reference_path, "r", encoding="utf-8-sig",
    errors="replace", newline=""
) as file:
    reference_header = next(csv.reader(file))

print("Reference file:", reference_path.name)
print("Reference column count:", len(reference_header))
print("First 5 columns:", reference_header[:5])
print("Last 5 columns:", reference_header[-5:])
print("Label column present:", "Label" in reference_header)

files_to_check = [
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv"
]

for filename in files_to_check:
    path = data_dir / filename
    field_counts = Counter()
    total_rows = 0
    examples = {}

    with open(
        path, "r", encoding="utf-8-sig",
        errors="replace", newline=""
    ) as file:
        reader = csv.reader(file)

        for line_number, row in enumerate(reader, start=1):
            total_rows += 1
            field_counts[len(row)] += 1

            if len(row) not in examples:
                examples[len(row)] = (line_number, row[:5], row[-3:])

    print("\n" + "=" * 75)
    print("FILE:", filename)
    print("Total physical CSV records:", total_rows)
    print("Field-count distribution:", field_counts.most_common(10))

    for count, (line_number, first_fields, last_fields) in examples.items():
        print(
            f"Example with {count} fields at line {line_number}: "
            f"first={first_fields}, last={last_fields}"
        )

Reference file: Friday-WorkingHours-Morning.pcap_ISCX.csv
Reference column count: 79
First 5 columns: [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets']
Last 5 columns: ['Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']
Label column present: False

===========================================================================
FILE: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Total physical CSV records: 1936
Field-count distribution: [(79, 1935), (20, 1)]
Example with 20 fields at line 1: first=['', '0', '0', '2', '70'], last=['0', '0', 'BENIGN']
Example with 79 fields at line 2: first=['53', '23802', '2', '2', '72'], last=['0', '0', 'BENIGN']

===========================================================================
FILE: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Total physical CSV records: 30146
Field-count distribution: [(79, 30145), (62, 1)]
Example with 62 fields at line 1: first=['71', '327', '3', '330', '165'], last=['0', '0', 'BENIGN']
Example with 79 fields at line 2: first=['443', '32027', '3', '4', '92'], last=['0', '0', 'BENIGN']

===========================================================================
FILE: Monday-WorkingHours.pcap_ISCX.csv
Total physical CSV records: 23158
Field-count distribution: [(79, 23156), (63, 1), (53, 1)]
Example with 63 fields at line 1: first=['0980', '0', '170980', '170980', '0'], last=['0', '0', 'BENIGN']
Example with 79 fields at line 2: first=['53', '48748', '2', '2', '92'], last=['0', '0', 'BENIGN']
Example with 53 fields at line 23158: first=['443', '61178524', '15', '12', '1354'], last=['0', '0', '65.70']

===========================================================================
FILE: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Total physical CSV records: 35224
Field-count distribution: [(79, 35223), (63, 1)]
Example with 63 fields at line 1: first=['33333', '27997.4466', '48496', '3', '3'], last=['0', '0', 'BENIGN']
Example with 79 fields at line 2: first=['21', '2784123', '6', '7', '31'], last=['0', '0', 'BENIGN']

In [ ]:

import csv
from pathlib import Path
from collections import Counter
import pandas as pd

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)

output_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/processed"
)
output_dir.mkdir(parents=True, exist_ok=True)

reference_path = data_dir / "Friday-WorkingHours-Morning.pcap_ISCX.csv"

# Read the reference schema and normalize its column names.
reference_columns = pd.read_csv(
    reference_path, nrows=0, encoding="utf-8-sig"
).columns.str.strip().tolist()

assert len(reference_columns) == 79, (
    f"Expected 79 reference columns, got {len(reference_columns)}"
)
assert reference_columns[-1] == "Label", (
    f"Unexpected final column: {reference_columns[-1]}"
)

csv_files = sorted(data_dir.glob("*.csv"))

loaded_frames = []
file_reports = []

for path in csv_files:
    valid_rows = []
    malformed_rows = []

    with open(
        path, "r", encoding="utf-8-sig",
        errors="replace", newline=""
    ) as file:
        reader = csv.reader(file)

        for line_number, row in enumerate(reader, start=1):
            # Only records with the reference feature count are accepted.
            if len(row) == len(reference_columns):
                valid_rows.append(row)
            else:
                malformed_rows.append({
                    "line_number": line_number,
                    "field_count": len(row),
                    "preview": row[:5],
                    "last_fields": row[-5:]
                })

    frame = pd.DataFrame(valid_rows, columns=reference_columns)

    # Remove accidental whitespace from labels and column names.
    frame["Label"] = frame["Label"].astype("string").str.strip()

    output_path = output_dir / f"{path.stem}_recovered.csv"
    frame.to_csv(output_path, index=False)

    loaded_frames.append(frame)

    file_reports.append({
        "file": path.name,
        "valid_rows": len(frame),
        "malformed_rows": len(malformed_rows),
        "label_missing": int(frame["Label"].isna().sum()),
        "output": str(output_path),
        "malformed_details": malformed_rows
    })

    print(f"\n{path.name}")
    print("  Valid records:", len(frame))
    print("  Malformed records:", len(malformed_rows))
    print("  Missing labels:", int(frame["Label"].isna().sum()))
    print("  Saved to:", output_path)

    for item in malformed_rows:
        print(
            "  MALFORMED:",
            f"line={item['line_number']},",
            f"fields={item['field_count']},",
            f"last_fields={item['last_fields']}"
        )

print("\nFinished reading all files.")
print("Files processed:", len(loaded_frames))
print("Reference columns:", len(reference_columns))

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
  Valid records: 1935
  Malformed records: 1
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX_recovered.csv
  MALFORMED: line=1, fields=20, last_fields=['0', '0', '0', '0', 'BENIGN']

Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
  Valid records: 30145
  Malformed records: 1
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX_recovered.csv
  MALFORMED: line=1, fields=62, last_fields=['0', '0', '0', '0', 'BENIGN']

Friday-WorkingHours-Morning.pcap_ISCX.csv
  Valid records: 191034
  Malformed records: 0
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Friday-WorkingHours-Morning.pcap_ISCX_recovered.csv

Monday-WorkingHours.pcap_ISCX.csv
  Valid records: 23156
  Malformed records: 2
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Monday-WorkingHours.pcap_ISCX_recovered.csv
  MALFORMED: line=1, fields=63, last_fields=['0', '0', '0', '0', 'BENIGN']
  MALFORMED: line=23158, fields=53, last_fields=['0', '0', '0', '0', '65.70']

Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
  Valid records: 35223
  Malformed records: 1
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX_recovered.csv
  MALFORMED: line=1, fields=63, last_fields=['0', '0', '0', '0', 'BENIGN']

Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
  Valid records: 170367
  Malformed records: 0
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX_recovered.csv

Tuesday-WorkingHours.pcap_ISCX.csv
  Valid records: 209817
  Malformed records: 1
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Tuesday-WorkingHours.pcap_ISCX_recovered.csv
  MALFORMED: line=209818, fields=27, last_fields=['17856.3385', '67754', '1', '162317', '11']

Wednesday-workingHours.pcap_ISCX.csv
  Valid records: 185944
  Malformed records: 1
  Missing labels: 0
  Saved to: /home/jupyter-itproject2026/TrustSOC/data/processed/Wednesday-workingHours.pcap_ISCX_recovered.csv
  MALFORMED: line=185945, fields=24, last_fields=['3', '99000000', '19800000', '44200000', '']

Finished reading all files.
Files processed: 8
Reference columns: 79

In [1]:

import pandas as pd
from pathlib import Path

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)
output_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/processed"
)

recovered_files = sorted(output_dir.glob("*_recovered.csv"))

all_frames = []
file_label_summaries = []
header_rows_removed = []

for path in recovered_files:
    df = pd.read_csv(path, low_memory=False)
    df.columns = df.columns.str.strip()

    # Remove header records accidentally included as data.
    header_mask = (
        df["Label"].astype("string").str.strip().eq("Label")
    )
    removed = int(header_mask.sum())

    if removed:
        header_rows_removed.append({
            "file": path.name,
            "header_rows_removed": removed
        })

    df = df.loc[~header_mask].copy()
    df["Label"] = df["Label"].astype("string").str.strip()

    # Report missing labels instead of silently assigning a class.
    missing_labels = int(df["Label"].isna().sum())

    counts = df["Label"].value_counts(dropna=False)

    for label, count in counts.items():
        file_label_summaries.append({
            "file": path.name,
            "label": str(label),
            "count": int(count),
            "percentage": round(count / len(df) * 100, 4)
            if len(df) else 0
        })

    print(
        f"{path.name}: {len(df):,} data rows; "
        f"{missing_labels} missing labels; "
        f"{removed} header rows removed"
    )

    all_frames.append(df)

combined_df = pd.concat(all_frames, ignore_index=True)

print("\nTOTAL DATASET SUMMARY")
print("Files:", len(recovered_files))
print("Combined rows:", f"{len(combined_df):,}")
print("Feature columns:", len(combined_df.columns) - 1)
print("Missing labels:", int(combined_df["Label"].isna().sum()))

print("\nHEADER ROWS REMOVED")
display(pd.DataFrame(header_rows_removed))

print("\nCLASS DISTRIBUTION — COMBINED DATASET")
combined_counts = combined_df["Label"].value_counts(dropna=False)

combined_summary = pd.DataFrame({
    "count": combined_counts,
    "percentage": (
        combined_counts / len(combined_df) * 100
    ).round(4)
})
display(combined_summary)

print("\nCLASS DISTRIBUTION — EACH FILE")
display(pd.DataFrame(file_label_summaries))

print("\nPotential label anomalies:")
print(
    combined_df["Label"]
    .value_counts(dropna=False)
    .tail(15)
)

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX_recovered.csv: 1,935 data rows; 0 missing labels; 0 header rows removed
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX_recovered.csv: 30,145 data rows; 0 missing labels; 0 header rows removed
Friday-WorkingHours-Morning.pcap_ISCX_recovered.csv: 191,033 data rows; 0 missing labels; 1 header rows removed
Monday-WorkingHours.pcap_ISCX_recovered.csv: 23,156 data rows; 0 missing labels; 0 header rows removed
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX_recovered.csv: 35,223 data rows; 0 missing labels; 0 header rows removed
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX_recovered.csv: 170,366 data rows; 0 missing labels; 1 header rows removed
Tuesday-WorkingHours.pcap_ISCX_recovered.csv: 209,816 data rows; 0 missing labels; 1 header rows removed
Wednesday-workingHours.pcap_ISCX_recovered.csv: 185,943 data rows; 0 missing labels; 1 header rows removed

TOTAL DATASET SUMMARY
Files: 8
Combined rows: 847,617
Feature columns: 78
Missing labels: 0

HEADER ROWS REMOVED

                                                file  header_rows_removed
0  Friday-WorkingHours-Morning.pcap_ISCX_recovere...                    1
1  Thursday-WorkingHours-Morning-WebAttacks.pcap_...                    1
2       Tuesday-WorkingHours.pcap_ISCX_recovered.csv                    1
3     Wednesday-workingHours.pcap_ISCX_recovered.csv                    1

CLASS DISTRIBUTION — COMBINED DATASET

                             count  percentage
Label
BENIGN                      706781     83.3845
DoS Hulk                    105457     12.4416
PortScan                      9027       1.065
FTP-Patator                   7938      0.9365
DoS slowloris                 5796      0.6838
DoS Slowhttptest              5499      0.6488
SSH-Patator                   2973      0.3507
Bot                           1966      0.2319
Web Attack � Brute Force      1507      0.1778
Web Attack � XSS               652      0.0769
Web Attack � Sql Injection      21      0.0025

CLASS DISTRIBUTION — EACH FILE

,file,label,count,percentage
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX_r...,BENIGN,1935,100.0000
1,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,BENIGN,21118,70.0547
2,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,PortScan,9027,29.9453
3,Friday-WorkingHours-Morning.pcap_ISCX_recovere...,BENIGN,189067,98.9709
4,Friday-WorkingHours-Morning.pcap_ISCX_recovere...,Bot,1966,1.0291
5,Monday-WorkingHours.pcap_ISCX_recovered.csv,BENIGN,23156,100.0000
6,Thursday-WorkingHours-Afternoon-Infilteration....,BENIGN,35223,100.0000
7,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,BENIGN,168186,98.7204
8,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � Brute Force,1507,0.8846
9,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � XSS,652,0.3827
10,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � Sql Injection,21,0.0123
11,Tuesday-WorkingHours.pcap_ISCX_recovered.csv,BENIGN,198905,94.7997
12,Tuesday-WorkingHours.pcap_ISCX_recovered.csv,FTP-Patator,7938,3.7833
13,Tuesday-WorkingHours.pcap_ISCX_recovered.csv,SSH-Patator,2973,1.4170
14,Wednesday-workingHours.pcap_ISCX_recovered.csv,DoS Hulk,105457,56.7147
15,Wednesday-workingHours.pcap_ISCX_recovered.csv,BENIGN,69191,37.2109
16,Wednesday-workingHours.pcap_ISCX_recovered.csv,DoS slowloris,5796,3.1171
17,Wednesday-workingHours.pcap_ISCX_recovered.csv,DoS Slowhttptest,5499,2.9574

Potential label anomalies:
Label
BENIGN                        706781
DoS Hulk                      105457
PortScan                        9027
FTP-Patator                     7938
DoS slowloris                   5796
DoS Slowhttptest                5499
SSH-Patator                     2973
Bot                             1966
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: Int64

In [2]:

import csv
from pathlib import Path

data_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC/data/raw/"
    "cicids2017/MachineLearningCVE"
)

files_to_check = [
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv",
    "Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv"
]

for filename in files_to_check:
    path = data_dir / filename
    raw_bytes = path.read_bytes()

    print("\n" + "=" * 75)
    print("FILE:", filename)
    print("Size (MB):", round(len(raw_bytes) / (1024 * 1024), 3))

    for encoding in ["utf-8-sig", "cp1252"]:
        try:
            text = raw_bytes.decode(encoding)
            print(f"\n{encoding}: decoding succeeded")

            reader = csv.reader(text.splitlines())
            shown = 0

            for row in reader:
                if len(row) == 79:
                    label = row[-1].strip()

                    if (
                        "Web Attack" in label
                        or "Infiltration" in label
                        or "DDoS" in label
                        or "PortScan" in label
                    ):
                        print("  Example label:", repr(label))
                        shown += 1

                        if shown == 3:
                            break

            if shown == 0:
                print("  No target attack labels found in scanned records.")

        except UnicodeDecodeError as error:
            print(f"\n{encoding}: decoding failed:", error)

===========================================================================
FILE: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Size (MB): 0.551

utf-8-sig: decoding succeeded
  No target attack labels found in scanned records.

cp1252: decoding succeeded
  No target attack labels found in scanned records.

===========================================================================
FILE: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Size (MB): 8.343

utf-8-sig: decoding succeeded
  Example label: 'PortScan'
  Example label: 'PortScan'
  Example label: 'PortScan'

cp1252: decoding succeeded
  Example label: 'PortScan'
  Example label: 'PortScan'
  Example label: 'PortScan'

===========================================================================
FILE: Monday-WorkingHours.pcap_ISCX.csv
Size (MB): 8.0

utf-8-sig: decoding succeeded
  No target attack labels found in scanned records.

cp1252: decoding succeeded
  No target attack labels found in scanned records.

===========================================================================
FILE: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Size (MB): 10.253

utf-8-sig: decoding succeeded
  No target attack labels found in scanned records.

cp1252: decoding succeeded
  No target attack labels found in scanned records.

===========================================================================
FILE: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Size (MB): 49.613

utf-8-sig: decoding succeeded
  Example label: 'Web Attack � Brute Force'
  Example label: 'Web Attack � Brute Force'
  Example label: 'Web Attack � Brute Force'

cp1252: decoding succeeded
  Example label: 'Web Attack ï¿½ Brute Force'
  Example label: 'Web Attack ï¿½ Brute Force'
  Example label: 'Web Attack ï¿½ Brute Force'

In [5]:

def create_soc_alert(row, alert_id):
    return {
        "alert_id": alert_id,
        "service": {
            "destination_port": row["Destination Port"]
        },
        "flow": {
            "duration": row["Flow Duration"],
            "forward_packets": row["Total Fwd Packets"],
            "backward_packets": row["Total Backward Packets"],
            "forward_bytes": row["Total Length of Fwd Packets"],
            "backward_bytes": row["Total Length of Bwd Packets"]
        },
        "traffic": {
            "bytes_per_second": row["Flow Bytes/s"],
            "packets_per_second": row["Flow Packets/s"],
            "forward_packets_per_second": row["Fwd Packets/s"],
            "backward_packets_per_second": row["Bwd Packets/s"]
        },
        "packet_characteristics": {
            "forward_length_mean": row["Fwd Packet Length Mean"],
            "backward_length_mean": row["Bwd Packet Length Mean"],
            "packet_length_mean": row["Packet Length Mean"],
            "packet_length_std": row["Packet Length Std"]
        },
        "timing": {
            "flow_iat_mean": row["Flow IAT Mean"],
            "flow_iat_std": row["Flow IAT Std"],
            "flow_iat_max": row["Flow IAT Max"],
            "flow_iat_min": row["Flow IAT Min"]
        },
        "tcp_flags": {
            "fin": row["FIN Flag Count"],
            "syn": row["SYN Flag Count"],
            "rst": row["RST Flag Count"],
            "psh": row["PSH Flag Count"],
            "ack": row["ACK Flag Count"],
            "urg": row["URG Flag Count"]
        },
        "connection": {
            "init_window_forward": row["Init_Win_bytes_forward"],
            "init_window_backward": row["Init_Win_bytes_backward"],
            "active_mean": row["Active Mean"],
            "idle_mean": row["Idle Mean"]
        },
        "raw_features": row.to_dict()
    }


sample_alert = create_soc_alert(
    X_sample.iloc[0],
    "ALERT_0001"
)

print("Alert ID:", sample_alert["alert_id"])
print("Label included:", "Label" in sample_alert)
print("Raw feature count:", len(sample_alert["raw_features"]))

Alert ID: ALERT_0001
Label included: False
Raw feature count: 78

In [6]:

def build_retrieval_plan(alert):
    service = alert.get("service", {})
    flow = alert.get("flow", {})
    traffic = alert.get("traffic", {})
    flags = alert.get("tcp_flags", {})
    timing = alert.get("timing", {})

    # Summarize only facts actually present in the alert.
    observed_facts = [
        f"Destination port: {service.get('destination_port')}",
        f"Flow duration: {flow.get('duration')}",
        f"Forward packets: {flow.get('forward_packets')}",
        f"Backward packets: {flow.get('backward_packets')}",
        f"Forward bytes: {flow.get('forward_bytes')}",
        f"Backward bytes: {flow.get('backward_bytes')}",
        f"Bytes per second: {traffic.get('bytes_per_second')}",
        f"Packets per second: {traffic.get('packets_per_second')}",
        f"TCP flags: {flags}",
        f"Flow inter-arrival timing: {timing}"
    ]

    # Broad exploratory query; this does not establish an attack.
    mitre_query = (
        "Enterprise cybersecurity knowledge about interpreting network "
        "traffic and connection-level telemetry. The observations include "
        "flow duration, packet and byte counts, traffic rates, TCP flags, "
        "and packet timing. Identify relevant techniques only when their "
        "documented behavior is supported by additional evidence. "
        "Do not assume a specific attack technique."
    )

    # Search NVD only if the alert contains relevant asset/vulnerability context.
    context_keys = [
        "software",
        "software_name",
        "software_version",
        "cve_id",
        "vulnerability_id",
        "affected_product"
    ]

    has_asset_context = any(
        alert.get(key) for key in context_keys
    )

    return {
        "alert_id": alert.get("alert_id"),
        "observed_facts": observed_facts,
        "mitre_query": mitre_query,
        "search_nvd": bool(has_asset_context),
        "nvd_reason": (
            "Asset or vulnerability context is available."
            if has_asset_context
            else (
                "Skipped: no software/version, CVE ID, or affected-product "
                "context is present in this alert."
            )
        ),
        "applicability_rule": (
            "Retrieved documents are candidates, not proof that a "
            "technique or vulnerability applies to this alert."
        )
    }


retrieval_plan = build_retrieval_plan(sample_alert)

print("ALERT:", retrieval_plan["alert_id"])

print("\nOBSERVED FACTS")
for fact in retrieval_plan["observed_facts"]:
    print("-", fact)

print("\nMITRE ATT&CK QUERY")
print(retrieval_plan["mitre_query"])

print("\nNVD SEARCH:", retrieval_plan["search_nvd"])
print(retrieval_plan["nvd_reason"])

print("\nAPPLICABILITY RULE")
print(retrieval_plan["applicability_rule"])

ALERT: ALERT_0001

OBSERVED FACTS
- Destination port: 3268
- Flow duration: 112740690
- Forward packets: 32
- Backward packets: 16
- Forward bytes: 6448
- Backward bytes: 1152
- Bytes per second: 67.41133126
- Packets per second: 0.425755776
- TCP flags: {'fin': '0', 'syn': '1', 'rst': '0', 'psh': '0', 'ack': '1', 'urg': '0'}
- Flow inter-arrival timing: {'flow_iat_mean': '2398738.085', 'flow_iat_std': '5798697.94', 'flow_iat_max': '16400000', 'flow_iat_min': '3'}

MITRE ATT&CK QUERY
Enterprise cybersecurity knowledge about interpreting network traffic and connection-level telemetry. The observations include flow duration, packet and byte counts, traffic rates, TCP flags, and packet timing. Identify relevant techniques only when their documented behavior is supported by additional evidence. Do not assume a specific attack technique.

NVD SEARCH: False
Skipped: no software/version, CVE ID, or affected-product context is present in this alert.

APPLICABILITY RULE
Retrieved documents are candidates, not proof that a technique or vulnerability applies to this alert.

In [10]:

from pathlib import Path
import json
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

project_dir = Path(
    "/home/jupyter-itproject2026/TrustSOC"
)

documents_path = (
    project_dir / "data/knowledge_base/mitre_attack/"
    "mitre_attack_documents.json"
)

# Load the saved MITRE ATT&CK documents.
with open(documents_path, "r", encoding="utf-8") as file:
    mitre_documents = json.load(file)

print("MITRE documents loaded:", len(mitre_documents))

# Reuse the model if it exists; otherwise load its cached/downloaded copy.
if "embedding_model" not in globals():
    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Rebuild the vector index from the saved documents.
mitre_texts = [
    document.get("text", "")
    for document in mitre_documents
]

mitre_embeddings = embedding_model.encode(
    mitre_texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

mitre_embeddings = np.asarray(
    mitre_embeddings, dtype="float32"
)

index = faiss.IndexFlatL2(mitre_embeddings.shape[1])
index.add(mitre_embeddings)


def retrieve_mitre_evidence(query, top_k=5):
    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True
    )
    query_embedding = np.asarray(
        query_embedding, dtype="float32"
    )

    distances, indices = index.search(
        query_embedding,
        min(top_k, len(mitre_documents))
    )

    results = []

    for distance, document_index in zip(
        distances[0], indices[0]
    ):
        if document_index < 0:
            continue

        document = mitre_documents[int(document_index)]

        results.append({
            "source": document.get("source", "MITRE ATT&CK"),
            "technique_id": document.get("technique_id"),
            "name": document.get("name"),
            "distance": float(distance),
            "description": document.get("description", ""),
            "tactics": document.get("tactics", []),
            "platforms": document.get("platforms", []),
            "is_subtechnique": document.get(
                "is_subtechnique", False
            )
        })

    return results


print("FAISS vectors:", index.ntotal)
print("Embedding dimensions:", index.d)
print("MITRE retriever restored successfully.")

MITRE documents loaded: 697

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/22 [00:00<?, ?it/s]

FAISS vectors: 697
Embedding dimensions: 384
MITRE retriever restored successfully.

In [11]:

# Retrieve candidate MITRE ATT&CK evidence.
mitre_results = retrieve_mitre_evidence(
    retrieval_plan["mitre_query"],
    top_k=5
)

print("ALERT:", retrieval_plan["alert_id"])
print("RETRIEVED CANDIDATES:", len(mitre_results))
print("=" * 75)

for i, item in enumerate(mitre_results, start=1):
    print(f"\nEVIDENCE {i}")
    print("Source:", "MITRE ATT&CK")
    print("Technique ID:", item.get("technique_id", "Unavailable"))
    print("Technique:", item.get("name", "Unavailable"))
    print("Retrieval distance:", item.get("distance", "Unavailable"))
    print("Tactics:", item.get("tactics", []))
    print("Platforms:", item.get("platforms", []))

    description = item.get("description", "")
    print("Description:", description[:700])

    print(
        "Applicability:",
        "NOT ESTABLISHED — semantic retrieval alone does not "
        "demonstrate that this technique occurred in the alert."
    )

ALERT: ALERT_0001
RETRIEVED CANDIDATES: 5
===========================================================================

EVIDENCE 1
Source: MITRE ATT&CK
Technique ID: T1016.001
Technique: Internet Connection Discovery
Retrieval distance: 0.9384105205535889
Tactics: ['discovery']
Platforms: ['Windows', 'Linux', 'macOS', 'ESXi']
Description: Adversaries may check for Internet connectivity on compromised systems. This may be performed during automated discovery and can be accomplished in numerous ways such as using [Ping](https://attack.mitre.org/software/S0097), <code>tracert</code>, and GET requests to websites, or performing initial speed testing to confirm bandwidth.

Adversaries may use the results and responses from these requests to determine if the system is capable of communicating with their C2 servers before attempting to connect to them. The results may also be used to identify routes, redirectors, and proxy servers.
Applicability: NOT ESTABLISHED — semantic retrieval alone does not demonstrate that this technique occurred in the alert.

EVIDENCE 2
Source: MITRE ATT&CK
Technique ID: T1590.004
Technique: Network Topology
Retrieval distance: 0.9498987197875977
Tactics: ['reconnaissance']
Platforms: ['PRE']
Description: Adversaries may gather information about the victim's network topology that can be used during targeting. Information about network topologies may include a variety of details, including the physical and/or logical arrangement of both external-facing and internal network environments. This information may also include specifics regarding network devices (gateways, routers, etc.) and other infrastructure.

Adversaries may gather this information in various ways, such as direct collection actions via [Active Scanning](https://attack.mitre.org/techniques/T1595) or [Phishing for Information](https://attack.mitre.org/techniques/T1598). Information about network topologies may also be exposed to a
Applicability: NOT ESTABLISHED — semantic retrieval alone does not demonstrate that this technique occurred in the alert.

EVIDENCE 3
Source: MITRE ATT&CK
Technique ID: T1049
Technique: System Network Connections Discovery
Retrieval distance: 0.9623584747314453
Tactics: ['discovery']
Platforms: ['ESXi', 'IaaS', 'Linux', 'macOS', 'Network Devices', 'Windows']
Description: Adversaries may attempt to get a listing of network connections to or from the compromised system they are currently accessing or from remote systems by querying for information over the network.

An adversary who gains access to a system that is part of a cloud-based environment may map out Virtual Private Clouds or Virtual Networks in order to determine what systems and services are connected. The actions performed are likely the same types of discovery techniques depending on the operating system, but the resulting information may include details about the networked cloud environment relevant to the adversary's goals. Cloud providers may have different ways in which their virtual network
Applicability: NOT ESTABLISHED — semantic retrieval alone does not demonstrate that this technique occurred in the alert.

EVIDENCE 4
Source: MITRE ATT&CK
Technique ID: T1070.007
Technique: Clear Network Connection History and Configurations
Retrieval distance: 0.9956543445587158
Tactics: ['stealth']
Platforms: ['Linux', 'macOS', 'Windows', 'Network Devices']
Description: Adversaries may clear or remove evidence of malicious network connections in order to clean up traces of their operations. Configuration settings as well as various artifacts that highlight connection history may be created on a system and/or in application logs from behaviors that require network connections, such as [Remote Services](https://attack.mitre.org/techniques/T1021) or [External Remote Services](https://attack.mitre.org/techniques/T1133). Defenders may use these artifacts to monitor or otherwise analyze network connections created by adversaries.

Network connection history may be stored in various locations. For example, RDP connection history may be stored in Windows Registry v
Applicability: NOT ESTABLISHED — semantic retrieval alone does not demonstrate that this technique occurred in the alert.

EVIDENCE 5
Source: MITRE ATT&CK
Technique ID: T1071.001
Technique: Web Protocols
Retrieval distance: 1.0016968250274658
Tactics: ['command-and-control']
Platforms: ['ESXi', 'Linux', 'macOS', 'Network Devices', 'Windows']
Description: Adversaries may communicate using application layer protocols associated with web traffic to avoid detection/network filtering by blending in with existing traffic. Commands to the remote system, and often the results of those commands, will be embedded within the protocol traffic between the client and server.

Protocols such as HTTP/S(Citation: CrowdStrike Putter Panda) and WebSocket(Citation: Brazking-Websockets) that carry web traffic may be very common in environments. HTTP/S packets have many fields and headers in which data can be concealed. An adversary may abuse these protocols to communicate with systems under their control within a victim network while also mimicking normal, expe
Applicability: NOT ESTABLISHED — semantic retrieval alone does not demonstrate that this technique occurred in the alert.

In [12]:

# Build a query from the types of observations actually available.
alert = sample_alert

alert_grounded_query = (
    "Cybersecurity analysis of observed network connection metadata. "
    "The telemetry contains flow duration, source-to-destination packet "
    "counts, forward and backward byte counts, traffic rates, TCP flags, "
    "packet lengths, and inter-arrival timing. "
    "Find ATT&CK techniques whose documented behavior could be investigated "
    "using network traffic evidence. Distinguish network-observable behavior "
    "from endpoint-only behavior. Do not infer that any technique occurred."
)

queries_to_compare = {
    "Previous generic query": retrieval_plan["mitre_query"],
    "Alert-grounded query": alert_grounded_query
}

for query_name, query_text in queries_to_compare.items():
    print("\n" + "=" * 80)
    print("QUERY:", query_name)

    results = retrieve_mitre_evidence(query_text, top_k=5)

    for rank, item in enumerate(results, start=1):
        print(
            f"{rank}. {item.get('technique_id')} — "
            f"{item.get('name')} | "
            f"distance={item.get('distance', float('nan')):.4f}"
        )

================================================================================
QUERY: Previous generic query
1. T1016.001 — Internet Connection Discovery | distance=0.9384
2. T1590.004 — Network Topology | distance=0.9499
3. T1049 — System Network Connections Discovery | distance=0.9624
4. T1070.007 — Clear Network Connection History and Configurations | distance=0.9957
5. T1071.001 — Web Protocols | distance=1.0017

================================================================================
QUERY: Alert-grounded query
1. T1016.001 — Internet Connection Discovery | distance=0.8120
2. T1049 — System Network Connections Discovery | distance=0.8305
3. T1070.007 — Clear Network Connection History and Configurations | distance=0.8370
4. T1016 — System Network Configuration Discovery | distance=0.8736
5. T1590.004 — Network Topology | distance=0.8749

In [13]:

def validate_mitre_evidence(alert, retrieved_evidence):
    validated = []

    for item in retrieved_evidence:
        technique_id = item.get("technique_id")
        technique_name = item.get("name")
        description = item.get("description", "")

        validated.append({
            "source": item.get("source", "MITRE ATT&CK"),
            "evidence_id": technique_id,
            "title": technique_name,
            "description": description,
            "retrieval_distance": item.get("distance"),
            "applicability_status": "insufficient_information",
            "reason": (
                "The alert contains network-flow statistics, but the "
                "available evidence does not establish the specific "
                "adversary behavior described by this technique."
            ),
            "missing_context": [
                "Direct evidence of the technique's documented behavior",
                "Relevant event or endpoint telemetry where applicable"
            ]
        })

    return {
        "alert_id": alert.get("alert_id"),
        "assessment": "insufficient_information",
        "validated_evidence": validated,
        "limitations": [
            "Semantic retrieval identifies candidate knowledge, not proof.",
            "No specific MITRE ATT&CK technique is established by this "
            "validation step.",
            "This conservative result does not mean the alert is benign."
        ]
    }


# Validate the results from the alert-grounded query.
grounded_results = retrieve_mitre_evidence(
    alert_grounded_query,
    top_k=5
)

validated_report = validate_mitre_evidence(
    sample_alert,
    grounded_results
)

print("Alert:", validated_report["alert_id"])
print("Overall assessment:", validated_report["assessment"])

for item in validated_report["validated_evidence"]:
    print("\n", item["evidence_id"], "-", item["title"])
    print("Status:", item["applicability_status"])
    print("Reason:", item["reason"])
    print("Distance:", round(item["retrieval_distance"], 4))

print("\nLimitations:")
for limitation in validated_report["limitations"]:
    print("-", limitation)

Alert: ALERT_0001
Overall assessment: insufficient_information

 T1016.001 - Internet Connection Discovery
Status: insufficient_information
Reason: The alert contains network-flow statistics, but the available evidence does not establish the specific adversary behavior described by this technique.
Distance: 0.812

 T1049 - System Network Connections Discovery
Status: insufficient_information
Reason: The alert contains network-flow statistics, but the available evidence does not establish the specific adversary behavior described by this technique.
Distance: 0.8305

 T1070.007 - Clear Network Connection History and Configurations
Status: insufficient_information
Reason: The alert contains network-flow statistics, but the available evidence does not establish the specific adversary behavior described by this technique.
Distance: 0.837

 T1016 - System Network Configuration Discovery
Status: insufficient_information
Reason: The alert contains network-flow statistics, but the available evidence does not establish the specific adversary behavior described by this technique.
Distance: 0.8736

 T1590.004 - Network Topology
Status: insufficient_information
Reason: The alert contains network-flow statistics, but the available evidence does not establish the specific adversary behavior described by this technique.
Distance: 0.8749

Limitations:
- Semantic retrieval identifies candidate knowledge, not proof.
- No specific MITRE ATT&CK technique is established by this validation step.
- This conservative result does not mean the alert is benign.

In [14]:

from pathlib import Path

PROJECT_DIR = Path("/home/jupyter-itproject2026/TrustSOC")
SCRIPTS_DIR = PROJECT_DIR / "scripts"

SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

print("Project folder:", PROJECT_DIR)
print("Demo scripts folder:", SCRIPTS_DIR)
print("Folder ready:", SCRIPTS_DIR.exists())

Project folder: /home/jupyter-itproject2026/TrustSOC
Demo scripts folder: /home/jupyter-itproject2026/TrustSOC/scripts
Folder ready: True

In [15]:

from pathlib import Path

script_path = SCRIPTS_DIR / "demo_threat_intel.py"

script_code = r'''
from pathlib import Path
import json
import argparse

import numpy as np
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer


PROJECT_DIR = Path(__file__).resolve().parent.parent

MITRE_DOCS_PATH = (
    PROJECT_DIR
    / "data"
    / "knowledge_base"
    / "mitre_attack"
    / "mitre_attack_documents.json"
)

SAMPLE_DATA_PATH = (
    PROJECT_DIR
    / "data"
    / "processed"
    / "Friday-WorkingHours-Morning.pcap_ISCX_recovered.csv"
)

MODEL_NAME = "all-MiniLM-L6-v2"


def load_mitre_documents():
    if not MITRE_DOCS_PATH.exists():
        raise FileNotFoundError(
            f"MITRE documents not found: {MITRE_DOCS_PATH}"
        )

    with open(MITRE_DOCS_PATH, "r", encoding="utf-8") as file:
        documents = json.load(file)

    if not documents:
        raise ValueError("The MITRE document collection is empty.")

    return documents


def build_mitre_index(documents, model):
    texts = [document.get("text", "") for document in documents]

    embeddings = model.encode(
        texts,
        show_progress_bar=True,
        convert_to_numpy=True
    )

    embeddings = np.asarray(embeddings, dtype="float32")

    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)

    return index


def retrieve_mitre_evidence(query, documents, model, index, top_k=5):
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )
    query_embedding = np.asarray(query_embedding, dtype="float32")

    distances, indices = index.search(
        query_embedding,
        min(top_k, len(documents))
    )

    results = []

    for distance, document_index in zip(distances[0], indices[0]):
        if document_index < 0:
            continue

        document = documents[int(document_index)]

        results.append({
            "source": document.get("source", "MITRE ATT&CK"),
            "technique_id": document.get("technique_id"),
            "name": document.get("name", "Unknown technique"),
            "description": document.get("description", ""),
            "distance": float(distance),
            "tactics": document.get("tactics", []),
            "platforms": document.get("platforms", [])
        })

    return results


def create_soc_alert(row, alert_id):
    return {
        "alert_id": alert_id,
        "service": {
            "destination_port": row.get("Destination Port")
        },
        "flow": {
            "duration": row.get("Flow Duration"),
            "forward_packets": row.get("Total Fwd Packets"),
            "backward_packets": row.get("Total Backward Packets"),
            "forward_bytes": row.get("Total Length of Fwd Packets"),
            "backward_bytes": row.get("Total Length of Bwd Packets")
        },
        "traffic": {
            "bytes_per_second": row.get("Flow Bytes/s"),
            "packets_per_second": row.get("Flow Packets/s"),
            "forward_packets_per_second": row.get("Fwd Packets/s"),
            "backward_packets_per_second": row.get("Bwd Packets/s")
        },
        "packet_characteristics": {
            "forward_length_mean": row.get("Fwd Packet Length Mean"),
            "backward_length_mean": row.get("Bwd Packet Length Mean"),
            "packet_length_mean": row.get("Packet Length Mean"),
            "packet_length_std": row.get("Packet Length Std")
        },
        "timing": {
            "flow_iat_mean": row.get("Flow IAT Mean"),
            "flow_iat_std": row.get("Flow IAT Std"),
            "flow_iat_max": row.get("Flow IAT Max"),
            "flow_iat_min": row.get("Flow IAT Min")
        },
        "tcp_flags": {
            "fin": row.get("FIN Flag Count"),
            "syn": row.get("SYN Flag Count"),
            "rst": row.get("RST Flag Count"),
            "psh": row.get("PSH Flag Count"),
            "ack": row.get("ACK Flag Count"),
            "urg": row.get("URG Flag Count")
        },
        "connection": {
            "init_window_forward": row.get("Init_Win_bytes_forward"),
            "init_window_backward": row.get("Init_Win_bytes_backward"),
            "active_mean": row.get("Active Mean"),
            "idle_mean": row.get("Idle Mean")
        }
    }


def build_retrieval_query(alert):
    return (
        "Cybersecurity analysis of observed network connection metadata. "
        "The telemetry contains flow duration, source-to-destination packet "
        "counts, forward and backward byte counts, traffic rates, TCP flags, "
        "packet lengths, and inter-arrival timing. Find MITRE ATT&CK "
        "techniques whose documented behavior could be investigated using "
        "network traffic evidence. Distinguish network-observable behavior "
        "from endpoint-only behavior. Do not infer that any technique occurred."
    )


def validate_mitre_evidence(alert, evidence):
    validated = []

    for item in evidence:
        validated.append({
            "source": item["source"],
            "technique_id": item["technique_id"],
            "name": item["name"],
            "description": item["description"],
            "distance": item["distance"],
            "status": "insufficient_information",
            "reason": (
                "The available flow statistics do not establish the specific "
                "adversary behavior described by this technique."
            )
        })

    return {
        "alert_id": alert["alert_id"],
        "assessment": "insufficient_information",
        "evidence": validated,
        "limitations": [
            "Semantic retrieval identifies candidate knowledge, not proof.",
            "No specific MITRE ATT&CK technique is established by this step.",
            "Insufficient information does not mean the alert is benign."
        ]
    }


def load_sample_alert(sample_number):
    if not SAMPLE_DATA_PATH.exists():
        raise FileNotFoundError(
            f"Processed sample CSV not found: {SAMPLE_DATA_PATH}"
        )

    # Read only the requested data row plus the header.
    frame = pd.read_csv(
        SAMPLE_DATA_PATH,
        skiprows=range(1, sample_number + 1),
        nrows=1,
        low_memory=False
    )

    frame.columns = frame.columns.str.strip()

    if frame.empty:
        raise ValueError(
            f"No data row found for sample number {sample_number}."
        )

    # The label is deliberately excluded from the alert.
    row = frame.iloc[0].drop(labels=["Label"], errors="ignore")
    return create_soc_alert(row, f"ALERT_{sample_number:04d}")


def print_report(alert, report):
    print("\n" + "=" * 72)
    print("TRUSTSOC | THREAT INTELLIGENCE AGENT")
    print("=" * 72)

    print("\nAlert ID:", alert["alert_id"])
    print("Destination port:", alert["service"]["destination_port"])
    print("Flow duration:", alert["flow"]["duration"])
    print("Forward packets:", alert["flow"]["forward_packets"])
    print("Backward packets:", alert["flow"]["backward_packets"])
    print("Forward bytes:", alert["flow"]["forward_bytes"])
    print("Backward bytes:", alert["flow"]["backward_bytes"])
    print("Traffic rate (bytes/sec):", alert["traffic"]["bytes_per_second"])
    print("TCP flags:", alert["tcp_flags"])

    print("\nOVERALL ASSESSMENT:", report["assessment"])
    print("\nRETRIEVED MITRE ATT&CK CANDIDATES")

    for item in report["evidence"]:
        print("\n" + "-" * 60)
        print(f'{item["technique_id"]} — {item["name"]}')
        print(f'Retrieval distance: {item["distance"]:.4f}')
        print(f'Applicability: {item["status"]}')
        print("Reason:", item["reason"])

        description = item["description"].replace("\n", " ").strip()
        if len(description) > 350:
            description = description[:350].rsplit(" ", 1)[0] + "..."
        print("MITRE description:", description)

    print("\nLIMITATIONS")
    for limitation in report["limitations"]:
        print("-", limitation)

    print("\n" + "=" * 72)


def main():
    parser = argparse.ArgumentParser(
        description="Run the TrustSOC Threat Intelligence demo."
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=1,
        help="One-based row number from the recovered CSV (default: 1)."
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of MITRE candidates to retrieve."
    )
    args = parser.parse_args()

    if args.sample < 1:
        parser.error("--sample must be at least 1.")
    if args.top_k < 1:
        parser.error("--top-k must be at least 1.")

    print("Loading MITRE ATT&CK documents...")
    documents = load_mitre_documents()
    print(f"Loaded {len(documents)} documents.")

    print(f"Loading embedding model: {MODEL_NAME}")
    model = SentenceTransformer(MODEL_NAME)

    print("Building FAISS index...")
    index = build_mitre_index(documents, model)
    print(f"Index ready: {index.ntotal} vectors.")

    print("Loading sample alert...")
    alert = load_sample_alert(args.sample)

    query = build_retrieval_query(alert)
    evidence = retrieve_mitre_evidence(
        query, documents, model, index, top_k=args.top_k
    )

    report = validate_mitre_evidence(alert, evidence)
    print_report(alert, report)


if __name__ == "__main__":
    main()
'''

script_path.write_text(script_code, encoding="utf-8")

print("Created:", script_path)
print("File exists:", script_path.exists())
print("Size:", script_path.stat().st_size, "bytes")

Created: /home/jupyter-itproject2026/TrustSOC/scripts/demo_threat_intel.py
File exists: True
Size: 9265 bytes

In [16]:

import json
from pathlib import Path

PROJECT_DIR = Path("/home/jupyter-itproject2026/TrustSOC")

documents_path = (
    PROJECT_DIR
    / "data"
    / "knowledge_base"
    / "mitre_attack"
    / "mitre_attack_documents.json"
)

with open(documents_path, "r", encoding="utf-8") as file:
    mitre_documents = json.load(file)

print("Total documents:", len(mitre_documents))
print("\nAvailable fields:")
print(list(mitre_documents[0].keys()))

print("\nExample document:")
for key, value in mitre_documents[0].items():
    if key == "description":
        value = value[:500] + "..." if len(value) > 500 else value
    print(f"{key}: {value}")

Total documents: 697

Available fields:
['source', 'type', 'name', 'technique_id', 'description', 'tactics', 'platforms', 'is_subtechnique', 'text']

Example document:
source: MITRE ATT&CK
type: attack-pattern
name: Extra Window Memory Injection
technique_id: T1055.011
description: Adversaries may inject malicious code into process via Extra Window Memory (EWM) in order to evade process-based defenses as well as possibly elevate privileges. EWM injection is a method of executing arbitrary code in the address space of a separate live process.

Before creating a window, graphical Windows-based processes must prescribe to or register a windows class, which stipulate appearance and behavior (via windows procedures, which are functions that handle input/output of data).(Citati...
tactics: ['stealth', 'privilege-escalation']
platforms: ['Windows']
is_subtechnique: True
text: Source: MITRE ATT&CK
Type: attack-pattern
Technique: Extra Window Memory Injection
Technique ID: T1055.011

Description:
Adversaries may inject malicious code into process via Extra Window Memory (EWM) in order to evade process-based defenses as well as possibly elevate privileges. EWM injection is a method of executing arbitrary code in the address space of a separate live process.

Before creating a window, graphical Windows-based processes must prescribe to or register a windows class, which stipulate appearance and behavior (via windows procedures, which are functions that handle input/output of data).(Citation: Microsoft Window Classes) Registration of new windows classes can include a request for up to 40 bytes of EWM to be appended to the allocated memory of each instance of that class. This EWM is intended to store data specific to that window and has specific application programming interface (API) functions to set and get its value. (Citation: Microsoft GetWindowLong function) (Citation: Microsoft SetWindowLong function)

Although small, the EWM is large enough to store a 32-bit pointer and is often used to point to a windows procedure. Malware may possibly utilize this memory location in part of an attack chain that includes writing code to shared sections of the process’s memory, placing a pointer to the code in EWM, then invoking execution by returning execution control to the address in the process’s EWM.

Execution granted through EWM injection may allow access to both the target process's memory and possibly elevated privileges. Writing payloads to shared sections also avoids the use of highly monitored API calls such as <code>WriteProcessMemory</code> and <code>CreateRemoteThread</code>.(Citation: Elastic Process Injection July 2017) More sophisticated malware samples may also potentially bypass protection mechanisms such as data execution prevention (DEP) by triggering a combination of windows procedures and other system functions that will rewrite the malicious payload inside an executable portion of the target process.  (Citation: MalwareTech Power Loader Aug 2013) (Citation: WeLiveSecurity Gapz and Redyms Mar 2013)

Running code in the context of another process may allow access to the process's memory, system/network resources, and possibly elevated privileges. Execution via EWM injection may also evade detection from security products since the execution is masked under a legitimate process.

Tactics:
stealth, privilege-escalation

Platforms:
Windows

Sub-technique:
True

In [17]:

def inspect_alert_evidence(alert):
    evidence_categories = {
        "network_flow": [
            "flow",
            "traffic",
            "service",
            "tcp_flags",
            "timing",
            "packet_characteristics"
        ],
        "endpoint_telemetry": [
            "process",
            "process_tree",
            "command_line",
            "endpoint_events"
        ],
        "identity_telemetry": [
            "user",
            "account",
            "authentication_events"
        ],
        "asset_and_vulnerability_context": [
            "software",
            "software_version",
            "cve_id",
            "affected_product",
            "asset"
        ],
        "security_event_context": [
            "event_type",
            "rule_name",
            "detection_reason",
            "source_alert"
        ]
    }

    result = {}

    for category, keys in evidence_categories.items():
        present = []
        missing = []

        for key in keys:
            value = alert.get(key)

            if value is not None and value != {} and value != "":
                present.append(key)
            else:
                missing.append(key)

        result[category] = {
            "present": present,
            "missing": missing
        }

    return result


# Use the sample alert created earlier in the notebook.
evidence_inventory = inspect_alert_evidence(sample_alert)

print("ALERT:", sample_alert.get("alert_id"))
print("=" * 60)

for category, details in evidence_inventory.items():
    print(f"\n{category.upper().replace('_', ' ')}")
    print("Available:", details["present"] or "None")
    print("Missing:", details["missing"] or "None")

ALERT: ALERT_0001
============================================================

NETWORK FLOW
Available: ['flow', 'traffic', 'service', 'tcp_flags', 'timing', 'packet_characteristics']
Missing: None

ENDPOINT TELEMETRY
Available: None
Missing: ['process', 'process_tree', 'command_line', 'endpoint_events']

IDENTITY TELEMETRY
Available: None
Missing: ['user', 'account', 'authentication_events']

ASSET AND VULNERABILITY CONTEXT
Available: None
Missing: ['software', 'software_version', 'cve_id', 'affected_product', 'asset']

SECURITY EVENT CONTEXT
Available: None
Missing: ['event_type', 'rule_name', 'detection_reason', 'source_alert']

In [19]:

def build_retrieval_query(alert):
    return (
        "Cybersecurity analysis of observed network connection metadata. "
        "The telemetry contains flow duration, forward and backward packet "
        "counts, byte counts, traffic rates, TCP flags, packet lengths, "
        "and inter-arrival timing. Identify MITRE ATT&CK techniques whose "
        "documented behavior could be investigated using network traffic. "
        "Distinguish network-observable behavior from endpoint-only behavior. "
        "Do not infer that any technique occurred."
    )


print("Retrieval query function restored successfully.")
print(build_retrieval_query(sample_alert))

Retrieval query function restored successfully.
Cybersecurity analysis of observed network connection metadata. The telemetry contains flow duration, forward and backward packet counts, byte counts, traffic rates, TCP flags, packet lengths, and inter-arrival timing. Identify MITRE ATT&CK techniques whose documented behavior could be investigated using network traffic. Distinguish network-observable behavior from endpoint-only behavior. Do not infer that any technique occurred.

In [20]:

def build_threat_intelligence_assessment(alert, retrieved_evidence):
    inventory = inspect_alert_evidence(alert)

    missing_context = []

    for category, details in inventory.items():
        if details["present"] == []:
            missing_context.append(category)

    validated_candidates = []

    for item in retrieved_evidence:
        validated_candidates.append({
            "source": item.get("source", "MITRE ATT&CK"),
            "technique_id": item.get("technique_id"),
            "technique_name": item.get("name"),
            "retrieval_distance": item.get("distance"),
            "applicability": "insufficient_information",
            "reason": (
                "The retrieved technique is a knowledge candidate. "
                "The current alert does not contain direct behavioral "
                "evidence establishing that this technique occurred."
            )
        })

    assessment = {
        "alert_id": alert.get("alert_id"),
        "agent": "Threat Intelligence Agent",
        "overall_assessment": "insufficient_information",
        "observed_telemetry": {
            category: details["present"]
            for category, details in inventory.items()
        },
        "missing_context": missing_context,
        "mitre_candidates": validated_candidates,
        "analyst_guidance": [
            "Review the underlying network flow and its surrounding traffic.",
            "Obtain endpoint or security-event telemetry if available.",
            "Do not treat semantic retrieval distance as threat confidence.",
            "Do not interpret insufficient information as a benign verdict."
        ]
    }

    return assessment


# Retrieve candidates and build the structured assessment.
demo_query = build_retrieval_query(sample_alert)

demo_candidates = retrieve_mitre_evidence(
    demo_query,
    mitre_documents,
    embedding_model,
    index,
    top_k=5
)

threat_intel_assessment = build_threat_intelligence_assessment(
    sample_alert,
    demo_candidates
)

print("ALERT:", threat_intel_assessment["alert_id"])
print("AGENT:", threat_intel_assessment["agent"])
print("ASSESSMENT:", threat_intel_assessment["overall_assessment"])

print("\nMISSING CONTEXT:")
for category in threat_intel_assessment["missing_context"]:
    print("-", category)

print("\nMITRE CANDIDATES:")
for item in threat_intel_assessment["mitre_candidates"]:
    print(
        f'{item["technique_id"]} — {item["technique_name"]} | '
        f'{item["applicability"]}'
    )
    print(" ", item["reason"])

print("\nANALYST GUIDANCE:")
for guidance in threat_intel_assessment["analyst_guidance"]:
    print("-", guidance)

TypeError: retrieve_mitre_evidence() got multiple values for argument 'top_k'

In [21]:
import inspect

print(inspect.signature(retrieve_mitre_evidence))

(query, top_k=5)

In [22]:
demo_candidates = retrieve_mitre_evidence(
    demo_query,
    top_k=5
)

In [23]:
threat_intel_assessment = build_threat_intelligence_assessment(
    sample_alert,
    demo_candidates
)

print("ALERT:", threat_intel_assessment["alert_id"])
print("AGENT:", threat_intel_assessment["agent"])
print("ASSESSMENT:", threat_intel_assessment["overall_assessment"])

print("\nMISSING CONTEXT:")
for category in threat_intel_assessment["missing_context"]:
    print("-", category)

print("\nMITRE CANDIDATES:")
for item in threat_intel_assessment["mitre_candidates"]:
    print(
        f'{item["technique_id"]} — {item["technique_name"]} '
        f'| {item["applicability"]}'
    )
    print(" ", item["reason"])

print("\nANALYST GUIDANCE:")
for guidance in threat_intel_assessment["analyst_guidance"]:
    print("-", guidance)

ALERT: ALERT_0001
AGENT: Threat Intelligence Agent
ASSESSMENT: insufficient_information

MISSING CONTEXT:
- endpoint_telemetry
- identity_telemetry
- asset_and_vulnerability_context
- security_event_context

MITRE CANDIDATES:
T1016.001 — Internet Connection Discovery | insufficient_information
  The retrieved technique is a knowledge candidate. The current alert does not contain direct behavioral evidence establishing that this technique occurred.
T1070.007 — Clear Network Connection History and Configurations | insufficient_information
  The retrieved technique is a knowledge candidate. The current alert does not contain direct behavioral evidence establishing that this technique occurred.
T1040 — Network Sniffing | insufficient_information
  The retrieved technique is a knowledge candidate. The current alert does not contain direct behavioral evidence establishing that this technique occurred.
T1016 — System Network Configuration Discovery | insufficient_information
  The retrieved technique is a knowledge candidate. The current alert does not contain direct behavioral evidence establishing that this technique occurred.
T1590 — Gather Victim Network Information | insufficient_information
  The retrieved technique is a knowledge candidate. The current alert does not contain direct behavioral evidence establishing that this technique occurred.

ANALYST GUIDANCE:
- Review the underlying network flow and its surrounding traffic.
- Obtain endpoint or security-event telemetry if available.
- Do not treat semantic retrieval distance as threat confidence.
- Do not interpret insufficient information as a benign verdict.

In [25]:

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

qwen_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

qwen_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
)

qwen_model.to(device)
qwen_model.eval()

print("Qwen model loaded successfully.")

Device: cuda

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Qwen model loaded successfully.

In [26]:

import json
import re

def explain_threat_assessment(assessment):
    allowed_input = {
        "alert_id": assessment["alert_id"],
        "overall_assessment": assessment["overall_assessment"],
        "observed_telemetry": assessment["observed_telemetry"],
        "missing_context": assessment["missing_context"],
        "mitre_candidates": [
            {
                "technique_id": item["technique_id"],
                "technique_name": item["technique_name"],
                "applicability": item["applicability"],
                "reason": item["reason"]
            }
            for item in assessment["mitre_candidates"]
        ],
        "analyst_guidance": assessment["analyst_guidance"]
    }

    prompt = f"""
You are explaining a structured cybersecurity assessment to a SOC analyst.

Use only the information in the JSON below.
Do not add IP addresses, hostnames, users, software, CVEs, attack claims,
or technical observations that are not explicitly present.
Do not change the assessment or claim that a candidate technique occurred.
Explain that missing context limits conclusions.
Use 3 to 5 short sentences.

STRUCTURED ASSESSMENT:
{json.dumps(allowed_input, ensure_ascii=False)}

Write the analyst explanation:
"""

    inputs = qwen_tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=2500
    ).to(device)

    with torch.no_grad():
        outputs = qwen_model.generate(
            **inputs,
            max_new_tokens=140,
            do_sample=False,
            pad_token_id=qwen_tokenizer.eos_token_id
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]
    explanation = qwen_tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    if not explanation:
        explanation = (
            "The assessment is inconclusive. Network-flow telemetry is "
            "available, but endpoint, identity, asset, and security-event "
            "context are missing. The retrieved MITRE ATT&CK techniques "
            "remain candidates rather than established findings."
        )

    return explanation


explanation = explain_threat_assessment(threat_intel_assessment)

print("QWEN ANALYST EXPLANATION")
print("=" * 60)
print(explanation)

QWEN ANALYST EXPLANATION
============================================================
To assess the severity of the incident, we need to identify the specific techniques used by the attacker and their associated endpoints. We should also investigate any potential vulnerabilities within the system or assets that could be exploited by the attacker. Additionally, we should consider the impact on the organization's operations and data security. Given the limited information provided, it is challenging to determine the exact nature of the attack or the extent of damage caused. Therefore, we must rely on the available telemetry data to make an informed conclusion about the incident's severity. In summary, we will need to review the network flow and its surrounding traffic, obtain endpoint or security-event telemetry if available, and analyze the potential for exploitation based on the available

In [27]:

def validate_qwen_explanation(explanation, assessment):
    text = explanation.strip()

    # Reject empty or visibly incomplete output.
    if not text or text[-1] not in ".!?":
        return False, "Output is empty or appears incomplete."

    # Reject common unsupported incident claims.
    unsupported_phrases = [
        "the attacker",
        "the attacker's",
        "extent of damage",
        "damage caused",
        "exploited by the attacker",
        "severity of the incident",
        "the vulnerability was exploited"
    ]

    lowered = text.lower()

    for phrase in unsupported_phrases:
        if phrase in lowered:
            return False, f"Potentially unsupported claim: {phrase}"

    return True, "Basic checks passed."


def create_deterministic_explanation(assessment):
    available = [
        category.replace("_", " ")
        for category, fields in assessment["observed_telemetry"].items()
        if fields
    ]

    missing = [
        category.replace("_", " ")
        for category in assessment["missing_context"]
    ]

    candidate_count = len(assessment["mitre_candidates"])

    available_text = ", ".join(available) if available else "none"
    missing_text = ", ".join(missing) if missing else "none"

    return (
        f'Alert {assessment["alert_id"]} has an overall assessment of '
        f'{assessment["overall_assessment"]}. Available telemetry includes '
        f'{available_text}. Missing context includes {missing_text}. '
        f'{candidate_count} MITRE ATT&CK candidates were retrieved, but '
        f'none is established as applicable by this assessment. '
        f'Insufficient information does not mean the alert is benign.'
    )


is_valid, validation_reason = validate_qwen_explanation(
    explanation,
    threat_intel_assessment
)

if is_valid:
    final_explanation = explanation
    explanation_source = "Qwen (passed basic output checks)"
else:
    final_explanation = create_deterministic_explanation(
        threat_intel_assessment
    )
    explanation_source = "Deterministic Python fallback"

print("Explanation source:", explanation_source)
print("Validation:", validation_reason)
print("\nFINAL ANALYST EXPLANATION")
print("=" * 60)
print(final_explanation)

Explanation source: Deterministic Python fallback
Validation: Output is empty or appears incomplete.

FINAL ANALYST EXPLANATION
============================================================
Alert ALERT_0001 has an overall assessment of insufficient_information. Available telemetry includes network flow. Missing context includes endpoint telemetry, identity telemetry, asset and vulnerability context, security event context. 5 MITRE ATT&CK candidates were retrieved, but none is established as applicable by this assessment. Insufficient information does not mean the alert is benign.

In [28]:
import inspect

print(inspect.getsource(build_retrieval_query))

def build_retrieval_query(alert):
    return (
        "Cybersecurity analysis of observed network connection metadata. "
        "The telemetry contains flow duration, forward and backward packet "
        "counts, byte counts, traffic rates, TCP flags, packet lengths, "
        "and inter-arrival timing. Identify MITRE ATT&CK techniques whose "
        "documented behavior could be investigated using network traffic. "
        "Distinguish network-observable behavior from endpoint-only behavior. "
        "Do not infer that any technique occurred."
    )

In [29]:

def build_retrieval_query(alert):
    service = alert.get("service", {})
    flow = alert.get("flow", {})
    traffic = alert.get("traffic", {})
    flags = alert.get("tcp_flags", {})
    timing = alert.get("timing", {})
    packet = alert.get("packet_characteristics", {})

    observations = [
        f"Destination port: {service.get('destination_port')}",
        f"Flow duration: {flow.get('duration')}",
        f"Forward packets: {flow.get('forward_packets')}",
        f"Backward packets: {flow.get('backward_packets')}",
        f"Forward bytes: {flow.get('forward_bytes')}",
        f"Backward bytes: {flow.get('backward_bytes')}",
        f"Bytes per second: {traffic.get('bytes_per_second')}",
        f"Packets per second: {traffic.get('packets_per_second')}",
        f"TCP flags: {flags}",
        f"Packet characteristics: {packet}",
        f"Flow timing: {timing}"
    ]

    observations_text = "\n".join(
        item for item in observations
        if not item.endswith(": None") and not item.endswith(": {}")
    )

    return (
        "Cybersecurity analysis of network-flow telemetry. "
        "Use the following observed values as context for retrieving "
        "potentially relevant MITRE ATT&CK knowledge. "
        "Do not assume that a port identifies an application or attack. "
        "Distinguish directly observed network behavior from endpoint-only "
        "behavior. Retrieved techniques are candidates, not confirmed findings.\n\n"
        "Observed alert data:\n"
        f"{observations_text}"
    )


print(build_retrieval_query(sample_alert))

Cybersecurity analysis of network-flow telemetry. Use the following observed values as context for retrieving potentially relevant MITRE ATT&CK knowledge. Do not assume that a port identifies an application or attack. Distinguish directly observed network behavior from endpoint-only behavior. Retrieved techniques are candidates, not confirmed findings.

Observed alert data:
Destination port: 3268
Flow duration: 112740690
Forward packets: 32
Backward packets: 16
Forward bytes: 6448
Backward bytes: 1152
Bytes per second: 67.41133126
Packets per second: 0.425755776
TCP flags: {'fin': '0', 'syn': '1', 'rst': '0', 'psh': '0', 'ack': '1', 'urg': '0'}
Packet characteristics: {'forward_length_mean': '201.5', 'backward_length_mean': '72', 'packet_length_mean': '163.3265306', 'packet_length_std': '178.9317127'}
Flow timing: {'flow_iat_mean': '2398738.085', 'flow_iat_std': '5798697.94', 'flow_iat_max': '16400000', 'flow_iat_min': '3'}

In [30]:

query_1 = build_retrieval_query(sample_alert)
results_1 = retrieve_mitre_evidence(query_1, top_k=5)

print("ALERT_0001 — Top candidates")
for item in results_1:
    print(
        item["technique_id"],
        item["name"],
        round(item["distance"], 4)
    )

ALERT_0001 — Top candidates
T1016.001 Internet Connection Discovery 0.7655
T1016 System Network Configuration Discovery 0.8327
T1205 Traffic Signaling 0.8359
T1071.001 Web Protocols 0.8467
T1205.002 Socket Filters 0.8677

In [31]:

from pathlib import Path
import pandas as pd

project_dir = Path("/home/jupyter-itproject2026/TrustSOC")
csv_path = (
    project_dir
    / "data"
    / "processed"
    / "Friday-WorkingHours-Morning.pcap_ISCX_recovered.csv"
)

df_compare = pd.read_csv(csv_path, low_memory=False)
df_compare.columns = df_compare.columns.str.strip()
df_compare = df_compare[
    df_compare["Label"].astype("string").str.strip() != "Label"
].copy()

# Exclude the ground-truth label from both alerts.
alert_1 = create_soc_alert(
    df_compare.drop(columns=["Label"]).iloc[0],
    "ALERT_0001"
)

alert_100 = create_soc_alert(
    df_compare.drop(columns=["Label"]).iloc[99],
    "ALERT_0100"
)

for alert in [alert_1, alert_100]:
    query = build_retrieval_query(alert)
    results = retrieve_mitre_evidence(query, top_k=5)

    print("\n" + "=" * 65)
    print("ALERT:", alert["alert_id"])
    print("Destination port:", alert["service"]["destination_port"])
    print("Top MITRE candidates:")

    for rank, item in enumerate(results, start=1):
        print(
            f'{rank}. {item["technique_id"]} — {item["name"]} '
            f'(distance={item["distance"]:.4f})'
        )

=================================================================
ALERT: ALERT_0001
Destination port: 3268
Top MITRE candidates:
1. T1016.001 — Internet Connection Discovery (distance=0.7655)
2. T1016 — System Network Configuration Discovery (distance=0.8327)
3. T1205 — Traffic Signaling (distance=0.8359)
4. T1071.001 — Web Protocols (distance=0.8467)
5. T1205.002 — Socket Filters (distance=0.8677)

=================================================================
ALERT: ALERT_0100
Destination port: 88
Top MITRE candidates:
1. T1016.001 — Internet Connection Discovery (distance=0.8221)
2. T1205 — Traffic Signaling (distance=0.8660)
3. T1016 — System Network Configuration Discovery (distance=0.8752)
4. T1071.001 — Web Protocols (distance=0.8793)
5. T1205.001 — Port Knocking (distance=0.9056)

In [32]:

def build_hybrid_retrieval_query(alert):
    service = alert.get("service", {})
    flow = alert.get("flow", {})
    traffic = alert.get("traffic", {})
    flags = alert.get("tcp_flags", {})

    port = service.get("destination_port")

    return f"""
Cybersecurity knowledge retrieval for a network-flow alert.

Observed telemetry:
- Destination port: {port}
- Flow duration: {flow.get("duration")}
- Forward packets: {flow.get("forward_packets")}
- Backward packets: {flow.get("backward_packets")}
- Forward bytes: {flow.get("forward_bytes")}
- Backward bytes: {flow.get("backward_bytes")}
- Bytes per second: {traffic.get("bytes_per_second")}
- Packets per second: {traffic.get("packets_per_second")}
- TCP flags: {flags}

Retrieval focus:
MITRE ATT&CK knowledge relevant to interpreting network connection
telemetry, communication patterns, traffic signaling, and observable
network behavior. Distinguish these from techniques requiring endpoint,
process, identity, or command-line evidence.

Do not assume a protocol or attack based on the port number alone.
Retrieved documents are candidate references, not confirmed findings.
"""


for alert in [alert_1, alert_100]:
    query = build_hybrid_retrieval_query(alert)
    results = retrieve_mitre_evidence(query, top_k=5)

    print("\n" + "=" * 65)
    print("ALERT:", alert["alert_id"])

    for rank, item in enumerate(results, start=1):
        print(
            f'{rank}. {item["technique_id"]} — {item["name"]} '
            f'(distance={item["distance"]:.4f})'
        )

=================================================================
ALERT: ALERT_0001
1. T1070.007 — Clear Network Connection History and Configurations (distance=0.7017)
2. T1016.001 — Internet Connection Discovery (distance=0.7146)
3. T1016 — System Network Configuration Discovery (distance=0.7259)
4. T1590.006 — Network Security Appliances (distance=0.7470)
5. T1518.001 — Security Software Discovery (distance=0.7498)

=================================================================
ALERT: ALERT_0100
1. T1016.001 — Internet Connection Discovery (distance=0.7404)
2. T1070.007 — Clear Network Connection History and Configurations (distance=0.7621)
3. T1016 — System Network Configuration Discovery (distance=0.7762)
4. T1590.006 — Network Security Appliances (distance=0.7956)
5. T1040 — Network Sniffing (distance=0.8116)

In [33]:

def apply_evidence_gate(alert, retrieved_evidence):
    inventory = inspect_alert_evidence(alert)

    has_endpoint = bool(
        inventory["endpoint_telemetry"]["present"]
    )
    has_identity = bool(
        inventory["identity_telemetry"]["present"]
    )
    has_asset_context = bool(
        inventory["asset_and_vulnerability_context"]["present"]
    )

    gated_candidates = []

    for item in retrieved_evidence:
        name = item.get("name", "Unknown technique")

        gated_candidates.append({
            "technique_id": item.get("technique_id"),
            "name": name,
            "retrieval_distance": item.get("distance"),
            "retrieval_status": "candidate_retrieved",
            "applicability": "insufficient_information",
            "investigation_priority": "unassessed",
            "reason": (
                "Semantic retrieval returned this candidate, but the "
                "current alert does not establish the behavior described "
                "by the technique."
            ),
            "available_context": {
                "network_flow": True,
                "endpoint_telemetry": has_endpoint,
                "identity_telemetry": has_identity,
                "asset_context": has_asset_context
            }
        })

    return {
        "alert_id": alert.get("alert_id"),
        "overall_assessment": "insufficient_information",
        "candidates": gated_candidates,
        "note": (
            "No candidate is confirmed by semantic retrieval alone. "
            "Investigation priority has not been assessed."
        )
    }


# Test the gate with the hybrid query results for ALERT_0001.
alert_1_results = retrieve_mitre_evidence(
    build_hybrid_retrieval_query(alert_1),
    top_k=5
)

gated_report = apply_evidence_gate(alert_1, alert_1_results)

print("Alert:", gated_report["alert_id"])
print("Assessment:", gated_report["overall_assessment"])

for candidate in gated_report["candidates"]:
    print(
        f'\n{candidate["technique_id"]} — {candidate["name"]}'
    )
    print("Retrieval:", candidate["retrieval_status"])
    print("Applicability:", candidate["applicability"])
    print("Investigation priority:", candidate["investigation_priority"])
    print("Reason:", candidate["reason"])

Alert: ALERT_0001
Assessment: insufficient_information

T1070.007 — Clear Network Connection History and Configurations
Retrieval: candidate_retrieved
Applicability: insufficient_information
Investigation priority: unassessed
Reason: Semantic retrieval returned this candidate, but the current alert does not establish the behavior described by the technique.

T1016.001 — Internet Connection Discovery
Retrieval: candidate_retrieved
Applicability: insufficient_information
Investigation priority: unassessed
Reason: Semantic retrieval returned this candidate, but the current alert does not establish the behavior described by the technique.

T1016 — System Network Configuration Discovery
Retrieval: candidate_retrieved
Applicability: insufficient_information
Investigation priority: unassessed
Reason: Semantic retrieval returned this candidate, but the current alert does not establish the behavior described by the technique.

T1590.006 — Network Security Appliances
Retrieval: candidate_retrieved
Applicability: insufficient_information
Investigation priority: unassessed
Reason: Semantic retrieval returned this candidate, but the current alert does not establish the behavior described by the technique.

T1518.001 — Security Software Discovery
Retrieval: candidate_retrieved
Applicability: insufficient_information
Investigation priority: unassessed
Reason: Semantic retrieval returned this candidate, but the current alert does not establish the behavior described by the technique.